import sys; sys.path.insert(0,'/tmp'); from navegador import *
fallas=0
def ok(c,m):
    global fallas; print(('  ✓ ' if c else '  ✗ ')+m); fallas += (0 if c else 1)
with sync_playwright() as pw:
    b, pg = abrir(pw, 'Dueno.html', 'du', idioma='es')
    pg.fill('#lEmail','javier'); pg.fill('#lPin','482915'); pg.evaluate("entrar()"); pg.wait_for_timeout(700)
    pg.evaluate("ir('obras')"); pg.wait_for_timeout(250)
    print('  alta de obra:')
    pg.evaluate("guardarObra()"); pg.wait_for_timeout(200)
    rojos = pg.evaluate("[...document.querySelectorAll('.falta')].map(e=>e.id||e.dataset.pies)")
    ok(len(rojos)>=5 and 'Faltan:' in pg.text_content('#toast'), 'crear vacía: %d campos en rojo y el aviso "%s…"' % (len(rojos), pg.text_content('#toast')[:40]))
    ok(pg.evaluate("getComputedStyle(document.querySelector('label.req'),'::after').content").strip('"').strip()=='*', 'los campos obligatorios llevan asterisco')
    pg.fill('#bCli','Familia Ortiz'); pg.fill('#bTel','512-555-0142'); pg.fill('#bDir','1400 Oak St'); pg.fill('#bMonto','28000')
    pg.select_option('#bAreas select','Cocina'); pg.fill('[data-pies="0"]','180'); pg.dispatch_event('[data-pies="0"]','change')
    ok(pg.evaluate("document.getElementById('bCli').classList.contains('falta')")==False, 'al escribir, el rojo se quita')
    val = lambda: pg.evaluate("[bCli.value,bTel.value,bDir.value,bMonto.value,document.querySelector('#bAreas select').value,document.querySelector('[data-pies=\"0\"]').value]")
    antes = val()
    pg.click('header .idioma'); pg.wait_for_timeout(300)
    ok(val()==antes, 'cambiar a inglés: nada se pierde %s' % antes[:3])
    ok('Client' in pg.text_content('#vista'), 'y los textos sí cambiaron a inglés')
    pg.click('header .idioma'); pg.wait_for_timeout(300)
    ok(val()==antes and 'Cliente' in pg.text_content('#vista'), 'regresar a español: todo sigue ahí')
    b.close()
    b, pg = abrir(pw, 'PM.html', 'pm', idioma='es')
    pg.fill('#lEmail','carlos'); pg.fill('#lPin','2468'); pg.evaluate("entrar()"); pg.wait_for_timeout(600)
    pg.evaluate("aplicarIdioma('es'); S.obra='OB-001'; ir('hoy')"); pg.wait_for_timeout(250)
    print('  cierre de día del PM a medio llenar:')
    pg.locator('#hCuad .opt').first.click(); pg.wait_for_timeout(60)
    if pg.locator('#hNota').count(): pg.fill('#hNota','Se atrasó el tile por lluvia')
    estado = lambda: pg.evaluate("[document.querySelectorAll('#hCuad .opt[data-on=\"1\"]').length, (document.getElementById('hNota')||{}).value||'']")
    antes = estado()
    pg.click('header .idioma'); pg.wait_for_timeout(300)
    ok(estado()==antes and antes[0]>=1, 'cambiar de idioma no borra la cuadrilla marcada ni lo escrito %s' % antes)
    b.close()
print('\n' + ('%d FALLAS' % fallas if fallas else 'TODO BIEN'))
