const fs=require('fs');
let fallas=0; const ok=(c,m)=>{ console.log((c?'  ✓ ':'  ✗ ')+m); if(!c) fallas++; };
delete require.cache[require.resolve('/tmp/harness.js')]; let H=require('/tmp/harness.js');
eval(fs.readFileSync('/home/claude/ijm/App_PM.gs','utf8')+'\nfunction __n(){for(const k in _memo) delete _memo[k];}');
console.log('\nEl idioma sigue a la persona');
let r=pmLogin('luis','1357'); ok(r.ok && r.idioma==='en', 'luis entra y el servidor le dice: inglés');
r=pmLogin('carlos','2468'); ok(r.idioma==='es', 'carlos: español');
pmIdioma(r.token,'en'); __n();
ok(pmLogin('carlos','2468').idioma==='en', 'carlos cambia a inglés con el botón: la próxima vez entra en inglés, en cualquier teléfono');
console.log('\nLos correos salen en el idioma del administrador');
let enviado=null; MailApp.sendEmail=(a,s,c)=>{ enviado={a,s,c}; };
guardarFotos_=()=>'x'; H.cache['pm_T']='carlos';
__n(); pmBloqueo('T',{obra:'OB-001',tipo:'Material',descripcion:'Falta el tile de la regadera, el proveedor no entregó',detiene:true});
ok(enviado && /^\[AVISO /.test(enviado.s) && /Detiene avance: SI/.test(enviado.c), 'administrador en español: "'+enviado.s+'"');
H.SHEETS['Usuarios'].find(u=>u[3]==='admin')[8]='en'; __n();
pmBloqueo('T',{obra:'OB-001',tipo:'Material',descripcion:'Falta el tile de la regadera, el proveedor no entregó',detiene:true});
ok(/^\[ALERT /.test(enviado.s) && /Work stopped: YES/.test(enviado.c), 'administrador en inglés: "'+enviado.s+'"');
ok(/Falta el tile de la regadera/.test(enviado.c), 'lo que escribió el PM llega tal cual: los datos no se traducen');
delete require.cache[require.resolve('/tmp/harness.js')]; H=require('/tmp/harness.js');
eval(fs.readFileSync('/home/claude/ijm/App_Dueno.gs','utf8')); H.cache['du_T']='javier';
console.log('\nLa orden de cambio para el cliente, en su idioma');
const es=duTextoOC('T','OC-0001','es'), en=duTextoOC('T','OC-0001','en');
ok(/ORDEN DE CAMBIO OC-0001/.test(es) && /MOTIVO: Condición oculta/.test(es) && /Autorizo:/.test(es), 'en español, como siempre');
ok(/CHANGE ORDER OC-0001/.test(en) && /REASON: Hidden condition/.test(en) && /NEW CONTRACT TOTAL/.test(en) && /Approved by:/.test(en), 'en inglés: título, motivo, total y firma');
ok(en.match(/\$[\d,]+/g).join()===es.match(/\$[\d,]+/g).join(), 'los montos son idénticos en los dos: '+en.match(/\$[\d,]+/g).slice(0,2).join(', ')+'…');
console.log('\n'+(fallas?fallas+' FALLAS':'TODO BIEN')); process.exit(fallas?1:0);
