import sys; sys.path.insert(0,'/tmp'); from navegador import *
fallas=0
def ok(c,m):
    global fallas; print(('  ✓ ' if c else '  ✗ ')+m); fallas += (0 if c else 1)
with sync_playwright() as pw:
    b, pg = abrir(pw, 'Dueno.html', 'du', idioma='es')
    pg.fill('#lEmail','javier'); pg.fill('#lPin','482915'); pg.evaluate("entrar()"); pg.wait_for_timeout(500)
    pg.evaluate("ir('catalogo')"); pg.wait_for_timeout(200)
    ok(pg.is_visible('#tNom') and pg.is_visible('#tPart'), 'Catálogo → "Nuevo tipo de obra" abre en blanco por defecto')
    pg.fill('#tNom','Piso de cemento'); pg.fill('#tPeso','40')
    pg.fill('#tPart','Protección y preparación de superficie\nReparación de grietas\nDesbaste y pulido\nAplicación de sellador')
    pg.click('text=Crear tipo'); pg.wait_for_timeout(700)
    ok('Piso de cemento' in pg.evaluate("S.d.tiposObra.join('|')"), 'se crea escribiendo las partidas una por renglón')
    ok(pg.locator('text=Desbaste y pulido').count()>0, 'y aparece en el catálogo con sus partidas')
    pg.click('text=+ Nuevo punto de control'); pg.wait_for_timeout(150)
    pg.fill('#hNom','PC6 Pre-sellado'); pg.fill('#hPunto','Superficie sin polvo ni humedad')
    pg.click('#formCat button:has-text("Crear")'); pg.wait_for_timeout(700)
    ok('PC6 Pre-sellado' in pg.evaluate("Object.keys(S.d.checklist).join('|')"), 'el punto de control nuevo se crea desde su botón')
    pg.click('text=+ Nuevo punto de control'); pg.wait_for_timeout(150)
    pg.fill('#hNom','PC3 Concreto'); pg.fill('#hPunto','x'); pg.click('#formCat button:has-text("Crear")'); pg.wait_for_timeout(500)
    ok('PC1 a PC5' in pg.inner_text('#toast'), 'con "PC3 Concreto" le explica por qué no: "%s…"' % pg.inner_text('#toast')[:60])
    i = pg.evaluate("S.d.partidas.findIndex(p=>p.tipo==='Piso de cemento' && p.partida==='Aplicación de sellador')")
    pg.evaluate("editarPartida(%d)" % i); pg.wait_for_timeout(150)
    opciones = pg.evaluate("[...document.querySelectorAll('#pHito option')].map(o=>o.value)")
    ok(opciones[0]=='' and 'PC6 Pre-sellado' in opciones, 'al editar una partida, el punto de control se escoge de una lista (%d opciones)' % len(opciones))
    pg.select_option('#pHito','PC6 Pre-sellado'); pg.click('#formCat button:has-text("Guardar")'); pg.wait_for_timeout(700)
    ok(pg.evaluate("S.d.partidas.find(p=>p.tipo==='Piso de cemento' && p.partida==='Aplicación de sellador').hito")=='PC6 Pre-sellado', 'y queda amarrado')
    pg.evaluate("ir('obras')"); pg.wait_for_timeout(150)
    ok('Piso de cemento' in pg.evaluate("[...document.querySelectorAll('#bAreas select option')].map(o=>o.value).join('|')"), 'el alta de obra ya lo ofrece para cada espacio')
    pg.click('header .idioma'); pg.evaluate("ir('catalogo')"); pg.wait_for_timeout(250)
    txt = pg.evaluate("document.getElementById('cardTipo').textContent")
    ok('Start from scratch' in txt and 'Tasks (one per line)' in txt and 'Create type' in txt, 'en inglés: "Start from scratch", "Tasks (one per line)", "Create type"')
    b.close()
print('\n' + ('%d FALLAS' % fallas if fallas else 'TODO BIEN'))
