# -*- coding: utf-8 -*-
# Traducciones al ingles de todo lo que ve un usuario. La clave es el texto en espanol
# tal como aparece en pantalla; el sistema traduce al mostrar, nunca al guardar.
EN = {
# ---------------------------------------------------------------- navegacion y titulos
"Hoy": "Today", "Gasto": "Expense", "Aviso": "Alert", "Obra": "Job", "Obras": "Jobs",
"Inicio": "Home", "Avisos": "Alerts", "Cambios": "Changes", "Subcontratos": "Subcontracts",
"Histórico": "History", "Catálogo": "Catalog", "Calidad": "Quality", "Secuencia": "Sequence",
"Fotos": "Photos", "Entrega": "Delivery", "Cuánto falta": "What's left", "Inspección": "Inspection",
"Levantar aviso": "Raise an alert", "Control de Obra": "Job Control", "Bitácora de Campo": "Field Log",
"Project Manager": "Project Manager", "Acceso de administrador": "Administrator access",
"Usuario": "Username", "PIN": "PIN", "Mostrar PIN": "Show PIN", "Ocultar PIN": "Hide PIN", "Entrar": "Sign in", "Entrar con otro usuario": "Sign in as another user",
"Correo": "Email", "Teléfono": "Phone", "Contacto": "Contact", "Nombre": "Name", "PM": "PM", "OK": "OK",
"Sí": "Yes", "No": "No", "sí": "yes", "no": "no", "Ver": "View", "Actualizar": "Refresh", "Entendido": "Got it",
"Reintentar": "Retry", "Cancelar": "Cancel", "Cerrar": "Close", "Guardar": "Save", "Borrar": "Delete",
"Editar": "Edit", "Crear": "Create", "Registrar": "Record", "Anular": "Void", "Llamar": "Call",
"Todavía no": "Not yet", "todo": "everything", "nunca": "never", "ahora": "now",
# ---------------------------------------------------------------- estados (datos: se traducen al mostrar)
"Sin iniciar": "Not started", "En progreso": "In progress", "Terminada": "Done",
"En obra": "In progress", "Lista para arranque": "Ready to start", "En cierre": "Closing out", "Entregada": "Delivered",
"Aprobado": "Approved", "aprobado": "approved", "Con defectos": "With defects", "con defectos": "with defects",
"Pendiente": "Pending", "Abierto": "Open", "Cerrado": "Closed", "Propuesta": "Proposed", "Autorizada": "Approved",
"Rechazada": "Rejected", "Facturada": "Billed", "Emitida": "Issued", "Confirmada": "Confirmed",
"Aprobada": "Approved", "Pagada": "Paid", "Cancelada": "Canceled", "Vigente": "Active", "Anulado": "Voided",
"En curso": "Running", "Sin fugas": "No leaks", "Con fuga": "Leak found", "toca ahora": "due now",
"más adelante": "later", "sin inspeccionar": "not inspected", "inspección aprobada": "inspection approved",
"vencido": "overdue", "listo": "done", "revisar": "review", "al día": "up to date", "al corriente": "all caught up",
# ---------------------------------------------------------------- catalogos fijos (datos)
"Material": "Material", "Renta equipo": "Equipment rental", "Herramienta": "Tools", "Permisos": "Permits",
"Disposicion": "Disposal", "Otro": "Other", "Cliente": "Client", "Sub": "Sub", "Condicion oculta": "Hidden condition",
"Diseno": "Design", "Defecto": "Defect", "Cambio de alcance": "Scope change", "Cambio": "Change",
"Expectativa": "Expectation", "Solicitud del cliente": "Client request", "Cambio de seleccion": "Selection change",
"Error de instalacion": "Installation error", "Error de especificacion": "Specification error",
"Error de estimacion": "Estimating error", "Material defectuoso": "Defective material",
"Falta de supervision": "Lack of supervision", "Deposito": "Deposit", "Hito": "Milestone",
"Orden de cambio": "Change order", "Liquidacion": "Final payment", "Anticipo": "Advance", "Parcial": "Partial",
"Transferencia": "Bank transfer", "Cheque": "Check", "Zelle": "Zelle", "Efectivo": "Cash", "Tarjeta": "Card",
"Tarjeta de la empresa": "Company card", "Por hora": "Hourly", "Por dia": "Daily rate",
"Generales": "General", "Bano": "Bathroom", "Cocina": "Kitchen", "Closet": "Closet",
"Generales de obra": "General conditions", "Baño": "Bathroom", "Baño principal": "Primary bathroom",
"Baño de visitas": "Guest bathroom", "Closet principal": "Primary closet",
"Retrabajo": "Rework", "Garantia": "Warranty", "Al autorizar": "On approval",
"50% al autorizar": "50% on approval", "Al siguiente hito": "At next milestone",
"pie2": "sq ft", "pie lineal": "linear ft", "pieza": "piece", "lote": "lot", "dia": "day",
"Plomeria": "Plumbing", "Electrico": "Electrical", "Tile": "Tile", "Demolicion": "Demolition",
"Countertops": "Countertops", "Drywall/Pintura": "Drywall/Paint",
# ---------------------------------------------------------------- partidas del catalogo de ejemplo
"Proteccion y movilizacion": "Protection and mobilization", "Permisos e inspecciones": "Permits and inspections",
"Contenedor y disposicion": "Dumpster and disposal", "Limpieza final y punch list": "Final clean and punch list",
"Demolicion y retiro de escombro": "Demolition and debris removal", "Rough de plomeria": "Plumbing rough-in",
"Rough electrico y extractor": "Electrical rough-in and exhaust fan", "Blocking y framing": "Blocking and framing",
"Inspeccion rough-in": "Rough-in inspection", "Cementboard y drywall": "Cement board and drywall",
"Impermeabilizacion + prueba de inundacion": "Waterproofing + flood test", "Tile de piso y muro": "Floor and wall tile",
"Lechada y sellado": "Grout and sealing", "Pintura primera mano": "Paint, first coat",
"Instalacion de vanity": "Vanity installation", "Plantilla de countertop": "Countertop template",
"Instalacion de countertop": "Countertop installation", "Plomeria final y luminarias": "Plumbing trim and light fixtures",
"Plantilla de puerta de vidrio": "Glass door template", "Instalacion de vidrio y accesorios": "Glass and accessories installation",
"Rough electrico": "Electrical rough-in", "Framing y blocking": "Framing and blocking", "Drywall y acabado": "Drywall and finish",
"Piso": "Flooring", "Instalacion de gabinetes": "Cabinet installation", "Backsplash": "Backsplash",
"Plomeria final": "Plumbing trim", "Electrico final y luminarias": "Electrical trim and light fixtures",
"Instalacion de appliances": "Appliance installation", "Reparacion de muros": "Wall repair", "Pintura": "Paint",
"Instalacion de estructura": "Closet system installation", "Instalacion de puertas y herrajes": "Doors and hardware installation",
"Iluminacion": "Lighting",
"PC1 Post demolicion": "PC1 Post-demolition", "PC2 Pre-cierre de muros": "PC2 Pre-wall close",
"PC3 Impermeabilizacion": "PC3 Waterproofing", "PC4 Pre-acabados": "PC4 Pre-finish", "PC5 Pre-entrega": "PC5 Pre-delivery",
# ---------------------------------------------------------------- checklist de calidad de ejemplo
"Estructura visible sin dano por agua ni termita": "Visible structure free of water or termite damage",
"Material de la plomeria existente identificado (galvanizado, PEX, cobre)": "Existing plumbing material identified (galvanized, PEX, copper)",
"Cableado sin aluminio; GFCI presente donde aplica": "No aluminum wiring; GFCI present where required",
"Subpiso nivelado, sin pudricion ni capas previas de tile": "Subfloor level, no rot or old tile layers",
"El extractor existente descarga al exterior, no al atico": "Existing exhaust fan vents outside, not into the attic",
"Muros medidos a nivel y plomo": "Walls checked for level and plumb",
"Sin evidencia de moho ni humedad previa": "No sign of mold or past moisture",
"Hallazgos levantados como aviso el mismo dia": "Findings raised as alerts the same day",
"Prueba de presion de plomeria sostenida": "Plumbing pressure test held",
"Drenaje con pendiente y ventilacion conectada": "Drain sloped with vent connected",
"Ubicaciones verificadas contra plano: regadera, desagues, salidas": "Locations checked against plan: shower, drains, outlets",
"Blocking para barras, banco, nichos, toallero y vanity": "Blocking for grab bars, bench, niches, towel bar and vanity",
"Circuitos dedicados y GFCI en su lugar": "Dedicated circuits and GFCI in place",
"Extractor con ducto aislado al exterior y damper": "Exhaust fan with insulated duct to the outside and damper",
"Alturas de salidas verificadas contra el diseno de tile": "Outlet heights checked against the tile layout",
"FOTO PANORAMICA DE CADA MURO COMPLETO antes de cubrir": "WIDE PHOTO OF EVERY FULL WALL before closing up",
"Sistema aplicado segun instrucciones del fabricante": "System applied per manufacturer instructions",
"Refuerzo en esquinas, juntas y penetraciones": "Reinforcement at corners, seams and penetrations",
"Pre-pendiente y pendiente correctas hacia el desague": "Correct pre-slope and slope to the drain",
"Desague con brida y sello correctos": "Drain with correct flange and seal",
"PRUEBA DE INUNDACION DE 24 HORAS documentada": "24-HOUR FLOOD TEST documented",
"Sin perforaciones posteriores a la prueba": "No penetrations after the test",
"Tile a nivel, a plomo y con juntas alineadas": "Tile level, plumb and with aligned joints",
"Sin piezas huecas (golpear con nudillo)": "No hollow tiles (knock test)",
"Lechada uniforme, sin faltantes y curada": "Grout even, complete and cured",
"Sellador en los cambios de plano, no lechada": "Caulk at change of plane, not grout",
"Gabinetes nivelados, a plomo y anclados a blocking": "Cabinets level, plumb and anchored to blocking",
"Puertas y cajones con holgura pareja": "Doors and drawers with even gaps",
"Superficie a nivel antes de tomar plantilla de countertop": "Surface level before countertop template",
"Plomeria probada: llaves, desagues, sanitario, sin fugas bajo vanity": "Plumbing tested: faucets, drains, toilet, no leaks under vanity",
"Puerta de regadera alineada, sellada y sin roce": "Shower door aligned, sealed and not rubbing",
"Iluminacion y extractor funcionando (extractor probado con papel)": "Lights and exhaust fan working (fan tested with paper)",
"Tomacorrientes probados; GFCI disparado y reseteado": "Outlets tested; GFCI tripped and reset",
"Cajones y puertas ajustados": "Drawers and doors adjusted", "Silicon parejo en todas las uniones": "Even caulk at every joint",
"Pintura sin marcas y tapas de registro colocadas": "Paint clean and access panels installed",
"Limpieza profunda hecha, incluye interior de gabinetes y vidrios": "Deep clean done, including inside cabinets and glass",
"Fotos finales para portafolio, misma toma que las del dia 1": "Final portfolio photos, same shots as day 1",
# ---------------------------------------------------------------- app del PM
"Cuatro pasos. Tres minutos.": "Four steps. Three minutes.",
"¿EN QUÉ SE TRABAJÓ?": "WHAT WAS WORKED ON?", "¿QUIÉN ESTUVO?": "WHO WAS THERE?", "FOTOS": "PHOTOS",
"¿ALGO FUERA DE LO NORMAL?": "ANYTHING OUT OF THE ORDINARY?", "terminó": "done",
"Opcional. Si algo te detiene, mejor levanta un aviso.": "Optional. If something is blocking you, raise an alert instead.",
"Cerrar el día": "Close the day", "Agregar fotos del avance": "Add progress photos",
"Tómalas ahora o elígelas de tu galería. Mínimo una.": "Take them now or pick them from your gallery. At least one.",
"Toca para agregar más": "Tap to add more", "Llegó": "Showed up", "No llegó": "No-show",
"Día cerrado": "Day closed", "✓ Día cerrado": "✓ Day closed", "reporte de hoy enviado": "today's report sent",
"Registrar otro movimiento de hoy": "Log something else for today", "Me equivoqué de obra, deshacer": "Wrong job, undo",
"días seguidos": "days in a row", "cerrados": "closed", "días": "days", "reportados": "reported",
"fotos": "photos", "subidas": "uploaded", "Faltan por cerrar": "Still to close", "Cerrar esta obra": "Close this job",
"RESPUESTA DEL ADMINISTRADOR": "ANSWER FROM THE ADMINISTRATOR", "Respuestas del administrador": "Answers from the administrator",
"INSPECCIÓN PENDIENTE": "INSPECTION PENDING",
"Esta partida no se puede cerrar hasta aprobarla. Lo que se cubre hoy no se vuelve a ver.":
  "This task can't be closed until it's approved. What gets covered today is never seen again.",
"Hacer la inspección": "Do the inspection", "Ver todos los puntos de control": "See all checkpoints",
"Reinspeccionar": "Reinspect", "Ya se hizo el trabajo: inspeccionar": "Work is done: inspect it",
"Marca lo que sí cumple. Lo que dejes sin marcar se registra como defecto y le llega al administrador.":
  "Check what passes. Anything left unchecked is logged as a defect and sent to the administrator.",
"REVISIÓN": "CHECKLIST", "requiere foto": "photo required", "requiere": "required",
"FOTOS DE LA INSPECCIÓN": "INSPECTION PHOTOS", "Agregar fotos": "Add photos",
"Cada muro completo, con cinta métrica donde ayude. Puedes elegirlas de tu galería.":
  "Every full wall, with a tape measure where it helps. You can pick them from your gallery.",
"Guardar inspección": "Save inspection", "Salir sin guardar": "Leave without saving",
"Prueba de inundación en curso": "Flood test running", "Falta la prueba de inundación": "Flood test missing",
"Arrancar la prueba": "Start the test", "Sin fugas, cerrar prueba": "No leaks, close the test",
"Bajó el nivel: hay fuga": "Level dropped: there's a leak", "✓ Prueba de inundación aprobada": "✓ Flood test approved",
"Foto del nivel ahora": "Water level photo now", "Foto del nivel al llenar": "Water level photo when filled",
"Con cámara: es la evidencia de las 24 horas.": "Camera only: it's the 24-hour evidence.",
"Tapa el desagüe, llena la zona húmeda y toma la foto del nivel. Vuelves en 24 horas con otra foto. Es el registro que te defiende de la reclamación de garantía más cara que existe.":
  "Plug the drain, fill the wet area and take a photo of the water level. Come back in 24 hours for another photo. It's the record that protects you from the most expensive warranty claim there is.",
"Vuelve cuando se cumplan las 24 horas. Cerrarla antes no prueba nada.": "Come back when the 24 hours are up. Closing it early proves nothing.",
"Tarjeta de la empresa, siempre.": "Company card, always.", "Monto": "Amount", "Categoría": "Category",
"¿Para qué partida?": "Which task is it for?", "— sin partida (va a Generales de obra) —": "— no task (goes to General conditions) —",
"Proveedor": "Vendor", "Qué compraste": "What you bought", "Recibo": "Receipt", "Foto del recibo": "Receipt photo",
"Registrar gasto": "Record expense", "Tus cargos sin recibo": "Your charges without a receipt", "Adjuntar recibo": "Attach receipt",
"¿Te equivocaste?": "Made a mistake?", "Ver mis capturas recientes": "See my recent entries",
"Home Depot, Ferguson…": "Home Depot, Ferguson…", "Tile 12x24 + thinset": "12x24 tile + thinset",
"¿Detiene el avance?": "Is work stopped?", "Sí, hay gente parada": "Yes, people are waiting", "No, puedo seguir": "No, I can keep going",
"Tipo": "Type", "Qué pasa y qué necesitas": "What's happening and what you need",
"Detrás del muro hay línea de acero galvanizado corroída. Necesito saber si se reemplaza antes de cerrar el muro.":
  "There's a corroded galvanized line behind the wall. I need to know if we replace it before closing the wall.",
"Fotos del problema": "Photos of the problem", "Enviar aviso": "Send alert", "Esperando respuesta": "Waiting for an answer",
"LO QUE SIGUE": "WHAT'S NEXT", "Lo que sigue": "What's next", "Sin sub asignado a esta partida.": "No sub assigned to this task.",
"No queda partida pendiente.": "No tasks left.", "Cambios autorizados": "Approved changes",
"Trabajo que el cliente ya firmó. Forma parte de la obra.": "Work the client already signed. It's part of the job.",
"CAMBIO AUTORIZADO POR EL CLIENTE": "CHANGE APPROVED BY THE CLIENT", "Medida verificada": "Measurement verified",
"Guardar medida": "Save measurement", "Pies²": "Sq ft", "Pies lineales": "Linear ft",
"Mídela en la visita de verificación. Es lo que convierte los costos en costo por pie².": "Measure it at the site visit. It's what turns costs into cost per sq ft.",
"Falta que confirmen": "Waiting for confirmation", "Confirmó por escrito": "Confirmed in writing",
"Subs en obra": "Subs on site", "Aprobar trabajo": "Approve work", "Lo que tardó cada partida": "How long each task took",
"Tu registro, para planear la próxima y para defender el tiempo cuando alguien diga que debió tardar menos.":
  "Your record, to plan the next one and to back up the time when someone says it should have taken less.",
"Llamar al cliente": "Call the client", "de avance": "complete", "de la obra": "overall",
"partidas": "tasks", "por hacer": "to do", "días para": "days to", "entregar": "delivery", "tarde": "late",
"aprobados": "approved", "por inspeccionar": "to inspect", "puntos de": "check-", "control": "points",
"Qué se revisa": "What's checked", "Ocultar": "Hide", "Toca": "Tap",
"para ver las preguntas de un punto antes de que toque. Así nada te agarra con el muro ya cerrado.":
  "to see a checkpoint's questions before it's due. That way nothing catches you with the wall already closed.",
"Todavía no hay fotos de esta obra.": "No photos for this job yet.",
"Las que subas en el cierre de día aparecen aquí.": "The ones you upload at the daily close show up here.",
"aviso": "alert", "Recorrido de entrega": "Delivery walkthrough", "Anota": "Write down",
"lo que señale el cliente, sin discutir nada en el momento. La clasificación se hace después, no enfrente de él.":
  "the client points out, without arguing anything on the spot. Sorting it comes later, not in front of them.",
"AGREGAR DETALLE": "ADD ITEM", "Silicón disparejo en la unión del vanity con el muro": "Uneven caulk where the vanity meets the wall",
"¿Qué es?": "What is it?", "¿Quién lo corrige?": "Who fixes it?", "Cuadrilla, Magaña Tile, yo…": "Crew, Magaña Tile, me…",
"Foto del detalle": "Photo of the item", "Opcional pero ayuda a quien lo va a corregir.": "Optional, but it helps whoever fixes it.",
"Agregar a la lista": "Add to the list", "Marcar corregido": "Mark fixed",
"Agrúpalos y ve una sola vez, no cinco viajes.": "Group them and go once, not five trips.",
"Cierra los pendientes que queden y listo.": "Close out whatever is left and you're done.",
"Se envía solo al volver la señal.": "It sends by itself when signal is back.",
"No cierres la app hasta que se envíe.": "Don't close the app until it sends.",
"Puedes corregir o cancelar lo que capturaste en las últimas 48 horas. Nada se borra: queda el registro de qué cambiaste y por qué.":
  "You can fix or cancel what you entered in the last 48 hours. Nothing is deleted: there's a record of what you changed and why.",
"Corregir": "Fix", "Cancelar este registro": "Cancel this entry", "Cancelado": "Canceled",
"Guardar corrección": "Save fix", "¿Por qué lo cambias?": "Why are you changing it?", "Capturé mal el monto": "I entered the wrong amount",
"Nada capturado en las últimas 48 horas.": "Nothing entered in the last 48 hours.", "Partida": "Task",
"— sin asignar —": "— unassigned —", "sin partida": "no task", "Horas": "Hours", "Descripcion": "Description",
# ---------------------------------------------------------------- app del administrador
"Lo que te toca hoy": "Your to-dos today", "Avisos por responder": "Alerts to answer",
"Responde hoy: es lo que sostiene que el PM siga reportando.": "Answer today: it's what keeps the PM reporting.",
"Órdenes de cambio sin autorizar": "Change orders not approved", "Perseguir la firma del cliente.": "Chase the client's signature.",
"Obras sin reporte": "Jobs without a report", "Más de dos días sin bitácora. Llamada al PM, no mensaje.": "More than two days without a daily log. Call the PM, don't text.",
"Subs con trabajo aprobado por pagar": "Subs with approved work to pay", "Aprobados por el PM y con saldo abierto.": "Approved by the PM with an open balance.",
"Cargos sin recibo": "Charges without a receipt", "Sin foto de recibo. El PM los adjunta desde su app.": "No receipt photo. The PM attaches them from the app.",
"Puntos de control con defectos": "Checkpoints with defects",
"El PM encontró defectos antes de cubrir. Decide quién los corrige y quién los paga.": "The PM found defects before closing up. Decide who fixes them and who pays.",
"Reclamos de garantía abiertos": "Open warranty claims", "Respuesta en 48 horas, visita de diagnóstico en 5 días.": "Answer within 48 hours, diagnostic visit within 5 days.",
"Pendientes de entrega vencidos": "Overdue delivery items", "Pasaron los 7 días hábiles. Agrupa y ve una sola vez.": "The 7 business days are up. Group them and go once.",
"Reseñas y visitas de garantía pendientes": "Reviews and warranty visits pending",
"Clientes recién entregados sin reseña, o garantías por vencer.": "Recently delivered clients without a review, or warranties about to expire.",
"Los avisos por correo no te están llegando": "You're not getting email alerts",
"Nada pendiente": "Nothing pending",
"Sin avisos abiertos, sin OC esperando firma y todas las obras reportaron. Buen momento para el bloque mensual: costear las obras cerradas.":
  "No open alerts, no change orders waiting for a signature, and every job reported. Good time for the monthly block: cost out closed jobs.",
"Los seis de cada lunes": "The Monday six", "Proceso 3": "Process 3", "Proceso 4": "Process 4", "Proceso 5": "Process 5", "Proceso 6": "Process 6",
"Control diario": "Daily control", "Control de cambios": "Change control", "Entrega y postventa": "Delivery and aftercare",
"Tasa de cierre de dia del PM (dias habiles)": "PM daily close rate (business days)",
"Integridad de tus datos. Si cae, todo lo demas es ficcion": "Your data integrity. If it drops, everything else is fiction",
"Obras que estan caminando a ciegas": "Jobs running blind", "Si tu fallas aqui, el PM deja de reportar": "If you fail here, the PM stops reporting",
"Horas promedio de respuesta a avisos": "Average hours to answer alerts", "Tu compromiso con el PM, medido": "Your commitment to the PM, measured",
"Cargos de tarjeta sin recibo": "Card charges without a receipt", "Control financiero de campo": "Field financial control",
"Gastos sin obra asignada": "Expenses without a job", "Un gasto sin obra contamina tu margen": "An expense without a job contaminates your margin",
"Tasa de presentacion de subs": "Sub show-up rate", "Calidad real de tu banco de subs": "The real quality of your sub bench",
"Ordenes de trabajo sin confirmacion escrita": "Work orders without written confirmation", "Cada una es un dia de obra en riesgo": "Each one is a work day at risk",
"Registros de cuadrilla sin partida asignada": "Crew entries without a task", "Sin partida no puedes costear la mano de obra": "Without a task you can't cost the labor",
"Horas de cuadrilla propia (7 dias)": "Own crew hours (7 days)", "Volumen de trabajo propio vs. subcontratado": "Own work vs. subcontracted volume",
"Pagos a subs sin trabajo aprobado por el PM": "Sub payments without PM-approved work", "Si pagas sin aprobacion, el control de calidad se cae solo": "If you pay without approval, quality control falls apart",
"Saldo pendiente con subcontratistas": "Balance owed to subcontractors", "Lo que ya debes aunque no haya salido de tu cuenta": "What you already owe even if it hasn't left your account",
"Dias de obra que estas perdiendo en espera": "Work days you're losing to waiting", "% de OC autorizadas": "% of change orders approved",
"Abajo de la meta: cotizas caro o comunicas mal": "Below target: you price too high or explain poorly",
"Margen promedio de las OC": "Average change order margin", "Si es menor al contrato base, te estas regalando": "If it's lower than the base contract, you're giving it away",
"Valor de OC sobre contratos": "Change order value over contracts", "Arriba de la meta el problema esta en tu estimacion": "Above target, the problem is in your estimating",
"Costo de no calidad sobre contratos": "Cost of poor quality over contracts", "El KPI que duele y que casi nadie mide": "The KPI that hurts and almost nobody tracks",
"Dias perdidos por retrabajo": "Days lost to rework", "Tiempo que pagaste dos veces": "Time you paid for twice",
"Inspecciones con evidencia fotografica": "Inspections with photo evidence", "Una inspeccion sin foto no es inspeccion": "An inspection without a photo is not an inspection",
"Encontrados a tiempo, antes de cubrirse. Esto es bueno que exista": "Caught in time, before being covered. It's good that these exist",
"Pruebas de inundacion con fuga": "Flood tests with a leak", "Cada una evitada es la reclamacion de garantia mas cara que existe": "Each one avoided is the most expensive warranty claim there is",
"Pruebas de inundacion documentadas": "Documented flood tests", "Tu defensa escrita si aparece humedad en dos anos": "Your written defense if moisture shows up in two years",
"Detalles por obra en el punch list del cliente": "Client punch list items per job",
"Punch list cerrado dentro de los 7 dias": "Punch list closed within 7 days", "Cerrar tarde es lo que arruina una entrega que salio bien": "Closing late is what ruins a delivery that went well",
"Pendientes del punch list vencidos": "Overdue punch list items", "Cada uno es un cliente esperando": "Each one is a client waiting",
"Reclamos de garantia por obra entregada": "Warranty claims per delivered job", "Lo que se te escapo. Es el espejo del KPI de calidad": "What slipped through. It mirrors the quality KPI",
"Costo de garantia sobre contratos": "Warranty cost over contracts", "Lo que te cuesta al ano volver a casas ya entregadas": "What it costs you each year to go back to delivered homes",
"Resenas obtenidas": "Reviews received", "Tu costo de adquisicion baja directo con esto": "Your acquisition cost drops directly with this",
"Horas de cuadrilla propia (7 dias) ": "Own crew hours (7 days)",
"Avance": "Progress", "Costo del presupuesto": "Budget spent", "Cobrado del contrato": "Contract collected",
"Captura el presupuesto para comparar el costo contra el avance": "Enter the budget to compare cost against progress",
"Contrato + OC": "Contract + COs", "Órdenes de cambio": "Change orders", "Costo comprometido": "Committed cost", "Margen corriente": "Current margin",
"Por cobrar": "To collect", "Falta pagar a subs": "Still owed to subs", "sin bitácora": "no daily log",
"Ver obra": "View job", "Nueva OC": "New CO", "OK ": "OK",
"Bloqueo abierto": "Open blocker", "Bloqueo fuera de SLA": "Blocker past SLA", "OC sin autorizar": "CO not approved",
"Alta de obra": "New job", "Cliente ": "Client", "Dirección": "Address", "Espacios que se van a remodelar": "Spaces to remodel",
"Generales de obra (permisos, contenedor, protección, limpieza final) se crea sola. Aquí van los espacios: un baño, dos baños, baño y cocina…":
  "General conditions (permits, dumpster, protection, final clean) is created automatically. List the spaces here: one bathroom, two bathrooms, bathroom and kitchen…",
"+ Agregar espacio": "+ Add space", "Quitar": "Remove", "Contrato total": "Total contract", "Entrega estimada": "Estimated delivery",
"Crear obra": "Create job", "Baño principal ": "Primary bathroom",
"Espacios de la obra": "Job spaces", "Espacio": "Space", "falta": "missing", "Nombre ": "Name",
"Si el cliente suma un espacio a media obra, agrégalo aquí y cóbralo con una orden de cambio.": "If the client adds a space mid-job, add it here and bill it with a change order.",
"Cobrado al cliente": "Collected from client", "Presupuestado por partida": "Budgeted by task",
"sin capturar: no se puede medir precisión": "not entered: accuracy can't be measured",
"Capturar presupuesto": "Enter budget", "Registrar cobro": "Record payment", "Cerrar obra": "Close job",
"Presupuesto contra real, por partida": "Budget vs. actual, by task",
"El desvío de cada partida es lo que corrige tu próxima cotización.": "Each task's variance is what corrects your next estimate.",
"Área": "Area", "Cant.": "Qty", "Presupuesto": "Budget", "Material ": "Material", "Cuadrilla": "Crew", "Real": "Actual",
"Unitario": "Unit cost", "Desvío": "Variance", "Avance por partida": "Progress by task", "Bitácora reciente": "Recent daily log",
"Sin bitácora.": "No daily log.", "ver fotos": "see photos", "Gastos capturados": "Recorded expenses", "Sin gastos.": "No expenses.",
"Cobros del cliente": "Client payments", "Sin cobros registrados.": "No payments recorded.", "Cuadrilla propia": "Own crew",
"Trabajador": "Worker", "Tiempo": "Time", "Costo": "Cost", "Sin horas registradas.": "No hours recorded.",
"Puntos de control": "Checkpoints", "Hito": "Checkpoint", "Puntos": "Points", "Resultado": "Result", "Defectos": "Defects",
"Sin inspecciones registradas todavía.": "No inspections recorded yet.", "Prueba de inundación": "Flood test",
"Sin prueba de inundación documentada": "No flood test documented", "foto inicio": "start photo", "foto fin": "end photo",
"Entrega sin registrar": "Delivery not recorded",
"El acta arranca el reloj de la garantía y la secuencia de reseña y referido. Regístrala el mismo día del recorrido con el cliente.":
  "The sign-off starts the warranty clock and the review and referral sequence. Record it the same day as the client walkthrough.",
"Fecha de entrega": "Delivery date", "Garantía en meses": "Warranty (months)", "¿Autoriza fotos?": "Photos authorized?",
"Notas del acta": "Sign-off notes", "Pendientes acordados, condiciones…": "Agreed pending items, conditions…", "Registrar entrega": "Record delivery",
"Cosecha comercial": "Sales follow-up", "Reseña pedida (día 3)": "Review requested (day 3)", "Reseña recibida": "Review received",
"Referido pedido (día 7)": "Referral requested (day 7)", "Visita de los 11 meses": "11-month visit", "hecho": "done", "marcar": "mark",
"Registrar reclamo de garantía": "Record warranty claim", "Punch list del cliente": "Client punch list", "Detalle": "Item",
"Qué es": "Type", "Responsable": "Responsible", "Compromiso": "Due", "Estado": "Status", "Cobrar": "Bill it",
"Lo marcado como": "Anything marked as", "no se regala: se cobra por orden de cambio.": "is not free: it's billed through a change order.",
"Reclamos de garantía": "Warranty claims", "Fecha": "Date", "Causa": "Cause", "Descripción": "Description",
"Qué reportó el cliente": "What the client reported", "Costo estimado": "Estimated cost", "Registrar reclamo": "Record claim",
"Sub responsable": "Responsible sub", "— ninguno —": "— none —",
"Presupuesto por partida": "Budget by task", "Cantidad": "Quantity", "Unidad": "Unit", "Guardar presupuesto": "Save budget",
"presupuestado": "budgeted", "margen presupuestado": "budgeted margin", "venta": "sales", "· costos fijos del proyecto": "· project fixed costs",
"Concepto": "Type", "Método": "Method", "Referencia": "Reference", "Ck 3341, ACH…": "Check 3341, ACH…",
"Al cerrar se congela la foto de esta obra en el histórico y sale del tablero.": "Closing freezes a snapshot of this job in History and removes it from the dashboard.",
"Todo en orden. Nada pendiente.": "All in order. Nothing pending.", "Contrato final": "Final contract", "Cobrado": "Collected",
"Presupuestado": "Budgeted", "Costo real": "Actual cost", "Margen bruto": "Gross margin", "Desvío de estimación": "Estimating variance",
"Días de obra": "Job days", "Costo de no calidad": "Cost of poor quality",
"Hay órdenes de cambio sin autorizar": "There are change orders not approved", "Hay órdenes de cambio autorizadas sin facturar": "There are approved change orders not billed",
"Hay órdenes de trabajo que el PM nunca aprobó": "There are work orders the PM never approved",
"Sin presupuesto por partida: esta obra no va a poder medir precisión de estimación": "No budget by task: this job won't be able to measure estimating accuracy",
"Hay costos sin partida asignada": "There are costs without a task", "La entrega al cliente no esta registrada": "The client delivery is not recorded",
"No hay avisos abiertos.": "No open alerts.",
"Responder en menos de 24 horas es lo que sostiene que el PM siga reportando.": "Answering in under 24 hours is what keeps the PM reporting.",
"detiene el avance": "work stopped", "FUERA DE SLA": "PAST SLA", "Tu respuesta": "Your answer",
"Qué hace el PM, con quién, para cuándo.": "What the PM does, with whom, by when.", "Responder y cerrar": "Answer and close",
"Convertir en OC": "Convert to CO", "+ Nueva orden de cambio": "+ New change order", "Registrar costo de no calidad": "Record cost of poor quality",
"Esperando autorización del cliente": "Waiting for client approval", "Historial": "History", "Sin órdenes de cambio.": "No change orders.",
"Precio": "Price", "Margen": "Margin", "Días": "Days", "Texto para el cliente": "Text for the client",
"Cliente autorizó": "Client approved", "Marcar cobrada": "Mark collected", "Copiar": "Copy",
"Nueva orden de cambio": "New change order", "Sin firma no se ejecuta. Cobra tu margen completo.": "No signature, no work. Charge your full margin.",
"Motivo": "Reason", "Fecha del hallazgo": "Date found", "Descripción para el cliente (sin tecnicismos)": "Description for the client (no jargon)",
"Tu costo": "Your cost", "Precio al cliente": "Price to client", "Días de impacto": "Schedule impact (days)",
"Condición de pago": "Payment terms", "Emitir OC": "Issue CO",
"Un error tuyo NO es orden de cambio. Se absorbe y se registra aquí. Es el dato que te dice qué sub y qué detalle constructivo te está costando dinero.":
  "Your own mistake is NOT a change order. You absorb it and record it here. It's the data that tells you which sub and which construction detail are costing you money.",
"Costo absorbido": "Cost absorbed", "Días perdidos": "Days lost", "Qué pasó": "What happened",
"Saldo pendiente con subs": "Balance owed to subs", "saldo pendiente con subs": "balance owed to subs",
"El pago va contra la orden de trabajo, nunca como gasto suelto. El costo se reconoce al emitir la orden, no al pagar.":
  "Payments go against the work order, never as a loose expense. The cost is recognized when the order is issued, not when paid.",
"+ Nueva orden de trabajo": "+ New work order", "Con saldo abierto": "With open balance", "Liquidadas o canceladas": "Paid off or canceled",
"Sin órdenes de trabajo.": "No work orders.", "partida:": "task:", "Precio cerrado": "Fixed price", "Pagado": "Paid",
"Saldo": "Balance", "Confirmó": "Confirmed", "PM aprobó": "PM approved", "Registrar pago": "Record payment",
"Nueva orden de trabajo": "New work order", "Precio cerrado y una partida. Sin eso no puedes costear ni comparar subs.":
  "A fixed price and a task. Without them you can't cost or compare subs.",
"Subcontratista": "Subcontractor", "Oficio": "Trade", "Partida que cubre": "Task covered", "Alcance (qué incluye y qué no)": "Scope (what's included and what's not)",
"Tile de piso y muro, incluye lechada y sellado. No incluye material ni retiro de escombro.": "Floor and wall tile, includes grout and sealing. Does not include material or debris removal.",
"Fecha de inicio": "Start date", "Fecha de fin": "End date", "Fin": "End", "Emitir orden": "Issue order",
"Banco de subcontratistas": "Subcontractor bench",
"La calificación no se captura: sale de si llegaron el día que dijeron y de los defectos que te costaron dinero.":
  "The rating isn't entered: it comes from whether they showed up when they said and from the defects that cost you money.",
"Órdenes": "Orders", "Puntualidad": "On-time rate", "Te costó": "It cost you", "Papeles": "Paperwork", "al día ": "up to date",
"sin W-9": "no W-9", "+ Agregar subcontratista": "+ Add subcontractor", "Nuevo subcontratista": "New subcontractor",
"Nombre o razón social": "Name or business name", "Tile, Plomeria, Electrico…": "Tile, Plumbing, Electrical…",
"Seguro vence": "Insurance expires", "Licencia estatal": "State license", "Solo plomería, eléctrico y A/C": "Plumbing, electrical and A/C only",
"Licencia vence": "License expires", "W-9 en archivo": "W-9 on file",
"El W-9 lo necesitas para el 1099 de fin de año de todo sub que te facture en el año. El seguro vencido te frena al pagarle.":
  "You need the W-9 for the year-end 1099 of every sub who bills you during the year. An expired insurance stops you when paying them.",
"Dar de baja": "Deactivate", "Cuadrilla propia ": "Own crew", "La tarifa costea la obra y": "The rate costs the job and",
"viaja a la app del PM. Un trabajador por día se captura en días, no en horas.": "travels to the PM app. A day-rate worker is entered in days, not hours.",
"Puesto": "Role", "Pago": "Pay", "Tarifa": "Rate", "+ Agregar trabajador": "+ Add worker",
"Editar trabajador": "Edit worker", "Nuevo trabajador": "New worker", "Tipo de pago": "Pay type", "Oficial de tile": "Tile setter",
"Registro de correcciones": "Corrections log",
"Nada se borra del sistema. Un registro equivocado se anula y queda el rastro de quién lo cambió y por qué. El PM puede corregir lo suyo dentro de 48 horas; tú, sin límite, salvo en obras ya cerradas.":
  "Nothing is deleted from the system. A wrong entry is voided and leaves a trail of who changed it and why. The PM can fix their own entries within 48 hours; you, without limit, except on closed jobs.",
"Ver el registro": "See the log", "Nada se borra del sistema. Esto es lo que se cambió y por qué.": "Nothing is deleted from the system. This is what changed and why.",
"Cuándo": "When", "Quién": "Who", "Qué": "What", "Sin correcciones todavía.": "No corrections yet.",
"Puntos de control de calidad": "Quality checkpoints", "Punto": "Checkpoint item", "Foto": "Photo", "+ Agregar punto": "+ Add item",
"Nuevo punto": "New item", "Editar punto": "Edit item", "Orden": "Order", "¿Requiere foto?": "Photo required?",
"Qué se revisa ": "What's checked", "Catálogo de partidas": "Task catalog", "Hito de calidad": "Quality checkpoint",
"Peso": "Weight", "% del tipo": "% of type", "+ Agregar partida": "+ Add task", "Nueva partida": "New task",
"Editar partida": "Edit task", "Tipo de obra": "Job type", "Orden en la secuencia": "Order in sequence",
"Peso (complejidad)": "Weight (complexity)", "Nombre de la partida": "Task name", "Hito de calidad (opcional)": "Quality checkpoint (optional)",
"El peso decide cuánto avanza la obra cuando esta partida se termina. Un baño completo suma 90; una partida de 18 es 20% del baño.":
  "The weight decides how much the job advances when this task is done. A full bathroom adds up to 90; an 18-point task is 20% of the bathroom.",
"Nuevo tipo de obra": "New job type",
"Empezar en blanco": "Start from scratch", "Copiar uno existente": "Copy an existing one",
"Para trabajos que no se parecen a los que ya tienes: un piso de cemento, una lavandería.": "For jobs that don't look like the ones you already have: a concrete floor, a laundry room.",
"Nombre del tipo": "Type name", "Piso de cemento, Lavandería…": "Concrete floor, Laundry…",
"Tamaño comparado con un baño": "Size compared to a bathroom", "Partidas (una por renglón)": "Tasks (one per line)",
"Protección y preparación de superficie\nReparación de grietas\nDesbaste y pulido\nAplicación de sellador": "Protection and surface prep\nCrack repair\nGrinding and polishing\nSealer application",
"El tamaño decide cuánto pesa este tipo en el avance de una obra combinada: un baño completo suma 90 y un closet 30. Se reparte parejo entre las partidas; después puedes afinar cada una y asignarles puntos de control.": "The size decides how much this type weighs in the progress of a combined job: a full bathroom adds up to 90 and a closet 30. It's split evenly across the tasks; later you can fine-tune each one and assign checkpoints.",
"Crear tipo": "Create type", "+ Nuevo punto de control": "+ New checkpoint", "Nuevo punto de control": "New checkpoint",
"Un punto de control es una inspección con fotos antes de cubrir o entregar. Después de crearlo, asígnalo a las partidas desde Editar partida.": "A checkpoint is a photo inspection before covering up or delivering. After creating it, assign it to tasks from Edit task.",
"Nombre del punto de control": "Checkpoint name", "PC6 Pre-sellado": "PC6 Pre-seal", "Primer punto a revisar": "First item to check",
"Base limpia, seca y sin grietas abiertas": "Surface clean, dry and free of open cracks", "— sin punto de control —": "— no checkpoint —",
"Punto de control creado": "Checkpoint created",
# ---------------------------------------------------------------- correcciones de la simulacion del mes
"Hoy no hubo trabajo aquí": "No work here today",
"Puntos que piden foto:": "Points that ask for a photo:", "Pedir foto solo en lo crítico": "Ask for photos only where critical",
"Tu día ya quedó cerrado.": "Your day is already closed.", "Fotos del cierre enviadas": "Close photos sent", "No encontré ese cierre.": "I couldn't find that close.", "Falta la foto.": "The photo is missing.",
"Plomería": "Plumbing", "Eléctrico": "Electrical", "Carpintería y muros": "Framing & walls", "Impermeabilización": "Waterproofing",
"Pintura": "Painting", "Vanity y countertop": "Vanity & countertop", "Vidrio y accesorios": "Glass & accessories", "Gabinetes": "Cabinets",
"Countertop": "Countertop", "Appliances": "Appliances", "Muros y pintura": "Walls & paint", "Sistema de closet": "Closet system",
"Tus etapas usan la agrupación anterior, por fase de la obra.": "Your stages use the previous grouping, by job phase.",
"Cambiarlas a una por tipo de trabajo": "Change them to one per type of work",
"Sistema": "System", "Respaldo semanal": "Weekly backup", "Activo: cada domingo a las 3 am": "Active: every Sunday at 3 am", "último": "last",
"No activado": "Not activated", "Sin información": "No information", "Respaldar ahora": "Back up now", "Activar respaldo semanal": "Activate weekly backup",
"Salud del libro": "Workbook health", "Sin revisar todavía": "Not checked yet", "problema(s)": "problem(s)", "revisado el": "checked on",
"Sin problemas": "No problems", "Revisar ahora": "Check now", "Protección de hojas": "Sheet protection",
"Protegidas con advertencia desde el": "Protected with a warning since", "Sin proteger: una edición a mano puede romper los cálculos": "Unprotected: a manual edit can break the calculations",
"Volver a proteger": "Protect again", "Proteger hojas": "Protect sheets", "Errores de los últimos 7 días": "Errors in the last 7 days",
"error(es)": "error(s)", "Ninguno": "None", "Errores del sistema": "System errors", "Problemas en el libro": "Workbook problems",
"Respaldo semanal sin activar": "Weekly backup not activated", "Días sin respaldo": "Days without a backup", "El libro está sano": "The workbook is healthy",
"Las dos apps corren con la cuenta de Google que las implementó. Que sea una cuenta del negocio, con verificación en dos pasos, no tu correo personal.": "Both apps run under the Google account that deployed them. Make it a business account with 2-step verification, not your personal email.",
"En los últimos 7 días. Si se repiten, pide que los revisen: están en Catálogo → Sistema.": "In the last 7 days. If they repeat, have them checked: they're in Catalog → System.",
"Columnas movidas, filas vacías o IDs repetidos: revísalos en Catálogo → Sistema.": "Moved columns, empty rows or repeated IDs: check them in Catalog → System.",
"Actívalo en Catálogo → Sistema: una copia del libro cada domingo.": "Activate it in Catalog → System: a copy of the workbook every Sunday.",
"El respaldo de cada domingo no ha corrido. Revísalo en Catálogo → Sistema.": "The Sunday backup hasn't run. Check it in Catalog → System.",
"No existe la hoja.": "The sheet does not exist.",
"Demolición": "Demolition", "Roughs": "Rough-ins", "Preparación e impermeabilización": "Prep & waterproofing", "Acabados": "Finishes",
"Instalaciones finales": "Final installs", "Muros y piso": "Walls & floor", "Gabinetes y countertop": "Cabinets & countertop",
"Preparación": "Prep", "Sistema e instalación": "System & install", "Otras partidas": "Other tasks",
"Presupuesto por etapa": "Budget by stage", "Captura el": "Enter the",
"que esperas en cada etapa: lo que vas a gastar en materiales, cuadrilla y subs, no lo que le cobras al cliente. Cotiza como siempre lo haces y aquí solo pon un monto por etapa.": "you expect for each stage: what you'll spend on materials, crew and subs, not what you charge the client. Quote the way you always do and just enter one amount per stage here.",
"tu promedio:": "your average:", "por pie²": "per sq ft", "sugerido": "suggested", "costo esperado": "expected cost", "contrato": "contract",
"Margen esperado:": "Expected margin:", "muy bajo: ¿capturaste precios en lugar de costos?": "very low: did you enter prices instead of costs?",
"muy alto: revisa que no falte alguna etapa": "very high: check that no stage is missing",
"Presupuesto contra real, por etapa": "Budget vs. actual, by stage",
"El costo real de cada etapa suma lo que se registró en sus partidas. El desvío de cada etapa es lo que corrige tu próxima cotización.": "Each stage's actual cost adds up what was recorded on its tasks. Each stage's variance is what corrects your next quote.",
"Etapa": "Stage", "Por pie²": "Per sq ft", "Materiales": "Materials", "Subs": "Subs", "cotizado": "quoted", "sin etapa": "no stage",
"Hay partidas sin duración o sin etapa: el cronograma les pone 1 día y el presupuesto las junta en Otras partidas.": "Some tasks have no duration or stage: the schedule gives them 1 day and the budget groups them under Other tasks.",
"Etapa del presupuesto": "Budget stage",
"Las etapas en rojo son las que siempre cotizas por debajo. Súbeles el costo en tu próxima cotización.": "Stages in red are the ones you always quote too low. Raise their cost on your next quote.",
"Sin presupuesto por etapa: esta obra no va a poder medir precisión de estimación": "No budget by stage: this job won't be able to measure estimating accuracy",
"Un monto no puede ser negativo.": "An amount cannot be negative.",
"cliente": "client", "teléfono del cliente": "client's phone", "dirección": "address", "fecha de inicio": "start date",
"fecha de entrega": "delivery date", "monto del contrato": "contract amount", "al menos un espacio": "at least one space",
"obra": "job", "subcontratista": "subcontractor", "alcance": "scope", "fecha de fin": "end date", "motivo": "reason",
"descripción": "description", "fecha del hallazgo": "discovery date", "costo": "cost", "monto": "amount", "concepto": "concept",
"método de pago": "payment method", "proveedor": "vendor", "qué se compró": "what was bought", "descripción del reclamo": "claim description",
"nombre": "name", "oficio": "trade", "teléfono": "phone", "tipo de pago": "pay type", "tarifa": "rate",
"El teléfono del cliente debe tener al menos 10 dígitos.": "The client's phone must have at least 10 digits.",
"Ese PM no existe o no está activo.": "That PM does not exist or is not active.",
"La fecha de entrega no puede ser antes del inicio.": "The delivery date cannot be before the start date.",
"La fecha de fin no puede ser antes del inicio.": "The end date cannot be before the start date.",
"TE FALTÓ CERRAR": "YOU MISSED A CLOSE", "Cerrarlo ahora": "Close it now",
"Se guarda con la fecha de ese día. Puedes usar fotos de hoy que muestren el trabajo.": "It's saved with that day's date. You can use today's photos that show the work.",
"Lo que se hizo ESE día. Queda marcado como cerrado tarde.": "What was done THAT day. It's marked as closed late.",
"+ Registrar día olvidado": "+ Record a missed day", "Día": "Day", "¿En qué se trabajó?": "What was worked on?",
"Para días más viejos que los 2 que el PM puede cerrar. Queda marcado como cerrado tarde.": "For days older than the 2 the PM can close. It's marked as closed late.",
"— nadie de la cuadrilla —": "— no crew —", "Horas (o días si es por día)": "Hours (or days if daily rate)",
"El PM estuvo sin teléfono y me lo dictó": "The PM had no phone and dictated it to me", "Día registrado": "Day recorded",
"Sin cierre hoy": "Not closed today", "Obras en curso que todavía no cierran el día. Una llamada ahora evita un día perdido.": "Active jobs that haven't closed the day yet. A call now saves a lost day.",
"Solo puedes cerrar los ultimos 2 dias habiles. Para dias mas viejos, pideselo al administrador.": "You can only close the last 2 business days. For older days, ask the administrator.",
"Ese dia ya tiene cierre en esta obra.": "That day already has a close on this job.", "Escribe por que lo registras tu y no el PM.": "Write why you're recording it and not the PM.",
"Elige el dia.": "Choose the day.", "Solo dias anteriores a hoy.": "Only days before today.", "Ese dia es antes del inicio de la obra.": "That day is before the job started.",
"Marca en que partida se trabajo ese dia.": "Check which task was worked on that day.", "(por día)": "(daily rate)",
"Sin presupuesto": "No budget", "Falta presupuesto": "Budget missing", "Capturar presupuesto": "Enter budget",
"Obras que no pueden arrancar": "Jobs that can't start", "Esta obra todavía no puede arrancar": "This job can't start yet",
"Falta que el administrador capture su presupuesto por partida. En cuanto lo haga, aquí te aparece el cierre de día.": "The administrator still needs to enter its budget by task. As soon as they do, the daily close shows up here.",
"Esta obra todavia no puede arrancar: falta que el administrador capture el presupuesto por partida.": "This job can't start yet: the administrator still needs to enter the budget by task.",
"Obra creada. Siguiente paso: su presupuesto por partida": "Job created. Next step: its budget by task",
"Esta semana": "This week", "Subs por programar en los próximos 5 días hábiles, sin orden de trabajo.": "Subs to schedule in the next 5 business days, with no work order.",
"Cronograma": "Schedule", "a tiempo con el plan": "on time with the plan", "Vidrio": "Glass", "Drywall": "Drywall",
"Punteado: el plan. Relleno: la previsión — verde terminado, ámbar recorrido.": "Dashed: the plan. Filled: the forecast — green done, amber pushed back.",
"con la anterior": "with the previous", "Días hábiles": "Business days", "Quién la hace": "Who does it", "Días de espera antes": "Wait days before",
"¿Arranca junto con la anterior?": "Starts with the previous one?", "Llenar las sugeridas": "Fill in the suggested ones",
"La espera es fabricación: el countertop después de su plantilla. \"Quién\" con el oficio de un sub hace que aparezca en \"subs por programar\".": "The wait is fabrication: the countertop after its template. Setting \"Who\" to a sub's trade makes it show up in \"subs to schedule\".",
"Hay partidas sin duración: el cronograma les pone 1 día.": "Some tasks have no duration: the schedule gives them 1 day.",
"Cumplimiento semanal del plan (PPC)": "Weekly plan completion (PPC)",
"De lo que estaba previsto terminar la semana pasada, cuanto se termino": "Of what was forecast to finish last week, how much got done",
"Nada previsto": "Nothing planned",
"Día completo": "Full day", "Medio día": "Half day", "medio día": "half day", "por día": "daily rate", "¿POR QUÉ NO HUBO TRABAJO?": "WHY WAS THERE NO WORK?",
"Esperando fabricacion": "Waiting on fabrication", "Esperando a un sub": "Waiting on a sub", "Esperando material": "Waiting on material",
"Esperando inspeccion": "Waiting on inspection", "Clima": "Weather", "Cliente no disponible": "Client unavailable",
"Opcional: qué se espera y para cuándo": "Optional: what we're waiting for and until when",
"También cuenta como día reportado. Si un sub no llegó, márcalo arriba antes de enviar.": "It also counts as a reported day. If a sub didn't show, mark it above before sending.",
"Reportar día sin trabajo": "Report a day without work", "Día reportado sin trabajo": "Day reported without work", "Día sin trabajo": "Day without work",
"Tu sesión expiró. Lo guardamos: entra de nuevo y se envía solo.": "Your session expired. We saved it: sign in again and it sends by itself.",
"Tu sesión expiró. Entra de nuevo antes de capturar.": "Your session expired. Sign in again before entering anything.",
"Elige por que no hubo trabajo hoy.": "Choose why there was no work today.",
"Obras atrasadas": "Late jobs", "Compras arriba del límite": "Purchases over the limit",
"El PM compró más de lo que puede sin autorización. Revísalas y márcalas.": "The PM bought more than allowed without approval. Review and mark them.",
"Revisada": "Reviewed", "Subs que no llegaron": "Subs who didn't show",
"Reprograma la orden: la falta queda contada y el PM marca cuando sí llegue.": "Reschedule the order: the no-show is counted and the PM marks when they do show up.",
"Reprogramar": "Reschedule", "+ agregar": "+ add", "quitar": "remove",
"¿Algo del catálogo no se hace en esta obra? Quítalo aquí: solo cambia esta obra.": "Something from the catalog isn't done on this job? Remove it here: it only changes this job.",
"+ Compra de la oficina": "+ Office purchase",
"Lo que compra la oficina — gabinetes, appliances — también es costo de la obra.": "What the office buys — cabinets, appliances — is also a job cost.",
"Qué se compró": "What was bought", "Gabinetes shaker blancos, 14 piezas": "White shaker cabinets, 14 pieces",
"Número de factura": "Invoice number", "Opcional": "Optional", "Registrar compra": "Record purchase",
"Compra registrada": "Purchase recorded", "Compra revisada": "Purchase reviewed",
"No se contrató en esta obra": "Not contracted on this job", "Partida quitada de esta obra": "Task removed from this job",
"Peso (complejidad). Un baño completo suma 90:": "Weight (complexity). A full bathroom adds up to 90:",
"Partida agregada a esta obra": "Task added to this job", "Nueva fecha de inicio": "New start date", "Nueva fecha de fin": "New end date",
"No llegó; confirmó para mañana a las 8": "Didn't show; confirmed for tomorrow at 8",
"La nueva fecha pide una nueva confirmación por escrito del sub.": "The new date needs a new written confirmation from the sub.",
"Orden reprogramada": "Order rescheduled", "Escribe por que se quita.": "Write why it's being removed.",
"Esa partida ya tiene avance, horas u ordenes de trabajo. Terminala en lugar de quitarla.": "That task already has progress, hours or work orders. Finish it instead of removing it.",
"Escribe el nombre de la partida.": "Write the task name.", "Pon la nueva fecha de inicio.": "Set the new start date.",
"La fecha de fin no puede ser antes del inicio.": "The end date can't be before the start.",

"No aplica": "N/A",
"Marca lo que sí cumple. Si una pregunta no aplica en esta obra, tócale No aplica. Lo que dejes sin marcar se registra como defecto y le llega al administrador.": "Check what passes. If a question doesn't apply to this job, tap N/A. Anything left unchecked is logged as a defect and sent to the administrator.",
"Una inspección necesita al menos un punto que aplique.": "An inspection needs at least one item that applies.",
"Una inspeccion necesita al menos un punto que aplique.": "An inspection needs at least one item that applies.",
"Este punto de control no tiene preguntas. Pidele al administrador que las agregue.": "This checkpoint has no questions. Ask the administrator to add them.",
"Ya existe un punto de control con ese nombre. Agrega sus puntos desde su tarjeta.": "A checkpoint with that name already exists. Add its items from its card.",
'"Generales" es el tipo que se crea solo en cada obra. Usa otro nombre.': '"General" is the type created automatically in every job. Use another name.',
"Escribe al menos una partida, una por renglon.": "Write at least one task, one per line.",
'PC1 a PC5 ya son los puntos de control de bano y cocina. Usa otro nombre, por ejemplo "PC6 Pre-sellado".': 'PC1 to PC5 are already the bathroom and kitchen checkpoints. Use another name, for example "PC6 Pre-seal".',
"Ese punto de control no existe. Crealo primero en Puntos de control de calidad.": "That checkpoint doesn't exist. Create it first under Quality checkpoints.", "Copia una secuencia existente y edítala. Más rápido que empezar de cero.": "Copy an existing sequence and edit it. Faster than starting from scratch.",
"Copiar desde": "Copy from", "Nombre del nuevo tipo": "New type name", "Medio baño, Lavandería…": "Half bath, Laundry…",
"Todavía no has cerrado ninguna obra.": "You haven't closed any jobs yet.",
"Cuando cierres la primera desde el detalle de obra, aquí empieza tu histórico. Es lo único que te dice si el negocio está mejorando.":
  "When you close the first one from the job detail, your history starts here. It's the only thing that tells you whether the business is improving.",
"Tus costos unitarios": "Your unit costs", "Ver el catálogo": "See the catalog", "Postventa": "Aftercare",
"Sin reclamos de garantía abiertos.": "No open warranty claims.", "Por tipo de obra": "By job type", "Mes a mes": "Month by month",
"Obras cerradas": "Closed jobs", "Cerrar reclamo": "Close claim", "reclamos por obra entregada": "claims per delivered job",
"costo de garantía acumulado": "total warranty cost", "reseñas obtenidas": "reviews received", "obras cerradas": "closed jobs",
"costo por pie²": "cost per sq ft", "Días de ciclo promedio": "Average cycle days", "Margen bruto promedio": "Average gross margin",
"Cobrado de lo entregado": "Collected on delivered work", "meta: menos de 5%": "target: under 5%", "meta: 35 a 45%": "target: 35 to 45%",
"meta: menos de 2%": "target: under 2%", "meta: menos de 1": "target: under 1", "meta: más de 60%": "target: over 60%",
"Las flechas comparan tus últimas 3 obras contra las 3 anteriores.": "The arrows compare your last 3 jobs against the 3 before them.",
"Si un tipo deja mucho menos que otro, el problema no es la obra: es qué estás vendiendo.": "If one type leaves much less than another, the problem isn't the job: it's what you're selling.",
"Mes": "Month", "Facturado": "Billed", "Entregada ": "Delivered", "Contrato": "Contract", "Garantía": "Warranty", "Reseña": "Review",
"Lo que de verdad te cuesta cada partida por unidad, con tus obras. Es el número con el que se cotiza, no la estimación.":
  "What each task really costs you per unit, from your own jobs. It's the number you estimate with, not the guess.",
"Tu costo": "Your cost", "Rango": "Range", "Cotizabas": "You quoted", "Diferencia": "Difference",
"Las partidas en rojo son las que siempre cotizas por debajo. Súbeles el unitario en tu próxima cotización.":
  "Tasks in red are the ones you always underquote. Raise their unit cost on your next estimate.",
"igual": "same", "Datos actualizados": "Data updated", "Hay datos nuevos": "There's new data",
"Te respondió el administrador": "The administrator answered you", "El cliente autorizó un cambio": "The client approved a change",
"Te asignaron una obra nueva": "You were assigned a new job", "Cambió la programación de subcontratistas": "The sub schedule changed",
"Nuevo aviso de obra": "New job alert", "Defectos en un punto de control": "Defects at a checkpoint", "Cargo sin recibo": "Charge without a receipt",
"Gasto nuevo": "New expense", "Cierre de día": "Daily close", "Horas de cuadrilla": "Crew hours", "Obra nueva": "New job",
# ---------------------------------------------------------------- avisos y toasts
"Agrega al menos una foto.": "Add at least one photo.", "Marca en qué partida se trabajó.": "Check which task was worked on.",
"Día cerrado ": "Day closed", "Sin conexión. Guardado, se envía solo.": "No connection. Saved, it will send by itself.",
"Sin conexión. Inténtalo al volver la señal.": "No connection. Try again when signal is back.",
"Todavía sin conexión. Lo guardamos.": "Still no connection. We saved it.", "Todo enviado": "All sent",
"Captura el monto.": "Enter the amount.", "Recibo adjuntado": "Receipt attached", "Gasto registrado": "Expense recorded",
"falta el recibo": "receipt missing", "Describe el bloqueo con detalle.": "Describe the blocker in detail.", "Aviso enviado": "Alert sent",
"Avance registrado": "Progress recorded", "Trabajo aprobado": "Work approved", "Confirmación registrada": "Confirmation recorded",
"La inspección necesita fotos.": "The inspection needs photos.", "Inspección aprobada": "Inspection approved",
"Toma la foto del nivel primero.": "Take the water level photo first.", "Prueba arrancada. Vuelve en 24 horas.": "Test started. Come back in 24 hours.",
"Fuga registrada": "Leak recorded", "avisado al administrador": "administrator notified", "Agregado a la lista": "Added to the list",
"Escribe qué señaló el cliente.": "Write what the client pointed out.", "Cerrado ": "Closed", "Registro cancelado": "Entry canceled",
"Medida guardada": "Measurement saved", "Catálogo actualizado": "Catalog updated", "Partida borrada": "Task deleted",
"Checklist actualizado": "Checklist updated", "Punto borrado": "Item deleted", "Cuadrilla actualizada": "Crew updated",
"Trabajador dado de baja": "Worker deactivated", "Cobro registrado": "Payment recorded", "Pago registrado": "Payment recorded", "Obra cerrada": "Job closed", "Reclamo registrado": "Claim recorded",
"Reclamo cerrado": "Claim closed", "Espacio agregado": "Space added", "Orden cancelada": "Order canceled",
"Subcontratista guardado": "Subcontractor saved", "Copiado. Pégalo en el correo al cliente.": "Copied. Paste it into the email to the client.",
"Registrado": "Recorded", "Anulado ": "Voided", "OC autorizada": "CO approved", "OC rechazada": "CO rejected", "OC facturada": "CO billed",
"Deshecho": "Undone", "Guardando…": "Saving…", "Entrando…": "Signing in…", "Enviando…": "Sending…", "Subiendo…": "Uploading…",
"Cargando…": "Loading…", "Cargando fotos…": "Loading photos…", "Cargando histórico…": "Loading history…", "Calculando…": "Calculating…",
"Sin conexión.": "No connection.", "Lo que registres se guarda y se envía solo.": "Whatever you record is saved and sends by itself.",
"No tienes obras asignadas.": "You have no jobs assigned.", "Esta obra no tiene puntos de control en su catálogo.": "This job has no checkpoints in its catalog.",
"Sin puntos definidos. Pídele al administrador que los agregue.": "No items defined. Ask the administrator to add them.",
"Todas las partidas están terminadas.": "All tasks are done.", "Sin cuadrilla dada de alta.": "No crew set up.",
"Tienes datos sin guardar en esta pantalla. ¿Actualizar de todos modos?": "You have unsaved data on this screen. Refresh anyway?",
"¿Aprobar el trabajo? El sub podrá cobrar. Solo apruebas lo que ya caminaste con él.": "Approve the work? The sub will be able to get paid. Only approve what you already walked with them.",
"¿Registrar fuga? Se le avisa al administrador y la impermeabilización no se aprueba.": "Record a leak? The administrator is notified and the waterproofing is not approved.",
"¿Ya quedó corregido?": "Is it fixed?", "¿Qué pasó? (se guarda el motivo)": "What happened? (the reason is saved)",
"Cerré la obra equivocada": "I closed the wrong job", "¿Por qué lo cancelas? (se guarda el motivo)": "Why are you canceling it? (the reason is saved)",
"Capturado por error": "Entered by mistake", "¿Por qué lo anulas? (queda registrado)": "Why are you voiding it? (it's logged)",
"¿Cuánto costó resolverlo? (deja vacío para no cambiarlo)": "How much did it cost to fix? (leave blank to keep it)",
"¿Confirmas que tienes la autorización POR ESCRITO del cliente?": "Do you confirm you have the client's approval IN WRITING?",
"¿Cancelar la orden? Deja de contar como costo comprometido de la obra.": "Cancel the order? It will stop counting as committed cost for the job.",
"¿Borrar este punto del checklist?": "Delete this checklist item?", "¿Dar de baja? Se conserva su historial de horas.": "Deactivate? Their hours history is kept.",
# ---------------------------------------------------------------- mensajes del servidor
"Usuario o PIN incorrectos.": "Wrong username or PIN.", "Demasiados intentos. Esta cuenta queda bloqueada 15 minutos.": "Too many attempts. This account is locked for 15 minutes.",
"Esta app es solo para Project Managers.": "This app is for Project Managers only.",
"Esta app es solo para administradores. Los PM usan Bitacora de Campo.": "This app is for administrators only. PMs use Field Log.",
"Sesion expirada. Vuelve a entrar.": "Session expired. Sign in again.", "Esa obra no esta asignada a ti.": "That job isn't assigned to you.",
"El cierre de dia requiere al menos una foto.": "The daily close needs at least one photo.", "Marca en que partida se trabajo hoy.": "Check which task was worked on today.",
"Captura un monto valido.": "Enter a valid amount.", "Todo gasto debe asignarse a una obra.": "Every expense must be assigned to a job.",
"Describe el bloqueo con detalle para que el administrador pueda resolverlo.": "Describe the blocker in detail so the administrator can solve it.",
"La inspeccion necesita fotos. Es la unica evidencia que va a quedar.": "The inspection needs photos. They're the only evidence that will remain.",
"La prueba arranca con la foto del nivel de agua.": "The test starts with a photo of the water level.",
"La prueba se cierra con la foto del nivel de agua.": "The test closes with a photo of the water level.",
"Ya hay una prueba en curso en esta area.": "There's already a test running in this area.", "Prueba no encontrada.": "Test not found.",
"Describe el detalle que senalo el cliente.": "Describe the item the client pointed out.", "Detalle no encontrado.": "Item not found.",
"Selecciona al menos un trabajador con horas.": "Select at least one worker with hours.", "Captura los pies cuadrados del area.": "Enter the area's square feet.",
"Area no encontrada.": "Area not found.", "Escribe el motivo de la correccion.": "Write the reason for the fix.",
"Escribe el motivo de la anulacion.": "Write the reason for voiding.", "Esa hoja no admite correcciones.": "That sheet doesn't allow fixes.",
"Esa hoja no admite anulaciones.": "That sheet doesn't allow voiding.",
"Ese registro lo capturo otra persona. Pidele al administrador que lo corrija.": "Someone else entered that record. Ask the administrator to fix it.",
"Ese registro lo capturo otra persona. Pidele al administrador que lo anule.": "Someone else entered that record. Ask the administrator to void it.",
"Esa obra ya esta cerrada. Su historico no se puede cambiar.": "That job is already closed. Its history can't be changed.",
"Ese registro ya esta anulado.": "That record is already voided.", "No cambiaste ningun valor.": "You didn't change any value.",
"El sistema esta ocupado con otra captura. Intenta de nuevo en unos segundos.": "The system is busy with another entry. Try again in a few seconds.",
"Falta configurar ID_CARPETA_DRIVE en la hoja Config.": "ID_CARPETA_DRIVE is not set in the Config sheet.",
"Esa obra ya esta cerrada.": "That job is already closed.", "Obra no encontrada.": "Job not found.", "OC no encontrada.": "Change order not found.",
"Orden de trabajo no encontrada.": "Work order not found.", "Partida no encontrada.": "Task not found.", "Punto no encontrado.": "Item not found.",
"Captura el precio al cliente.": "Enter the price to the client.", "Captura el monto del pago.": "Enter the payment amount.",
"Captura el monto del cobro.": "Enter the payment amount.", "Escribe una respuesta util para el PM.": "Write a useful answer for the PM.",
"Asigna la partida que cubre esta orden. Sin partida no hay costeo.": "Assign the task this order covers. Without a task there's no costing.",
"La orden va con precio cerrado, no abierta.": "The order must have a fixed price, not open-ended.",
"Esa orden ya tiene pagos. Ajusta el alcance en vez de cancelarla.": "That order already has payments. Adjust the scope instead of canceling it.",
"Tipo de obra y nombre de la partida son obligatorios.": "Job type and task name are required.",
"El tipo de obra origen no tiene partidas.": "The source job type has no tasks.", "Escribe el nombre del nuevo tipo de obra.": "Write the name of the new job type.",
"El nombre es obligatorio.": "The name is required.", "Nombre y oficio son obligatorios.": "Name and trade are required.",
"Hito y punto son obligatorios.": "Checkpoint and item are required.", "Agrega al menos un espacio: bano, cocina, closet...": "Add at least one space: bathroom, kitchen, closet...",
"Elige el tipo del espacio.": "Choose the space type.", "Esta obra ya tiene entrega registrada.": "This job already has a delivery recorded.",
"Esta obra no tiene entrega registrada.": "This job has no delivery recorded.", "Campo invalido.": "Invalid field.",
"Esta obra no tiene areas. Corre migrarAreas o dalas de alta.": "This job has no areas. Run migrarAreas or add them.",
"no tienes registrada la fecha de su seguro": "you don't have their insurance date on file",
"Esa partida ya tiene avance o mano de obra registrada.": "That task already has progress or labor recorded.",
}

# Reglas para textos que llevan numeros o datos adentro. Van en JavaScript tal cual.
PATRONES_JS = r"""
[/^(\$[\d,.]+) de (\$[\d,.]+)$/, '$1 of $2'],
[/^\+(\d+) días por OC$/, '+$1 days from COs'],
[/^\+(\d+)% en curso$/, '+$1% in progress'],
[/^\+(\d+) días por cambios autorizados$/, '+$1 days from approved changes'],
[/^\+(\d+) d$/, '+$1 d'],
[/^(\d+) de (\d+) aprobados$/, '$1 of $2 approved'],
[/^(\d+) de (\d+) puntos$/, '$1 of $2 points'],
[/^(\d+) de (\d+) partidas$/, '$1 of $2 tasks'],
[/^(\d+) de (\d+)$/, '$1 of $2'],
[/^([\d.]+) h de cuadrilla esta semana$/, '$1 crew hours this week'],
[/^(\d+)% de avance$/, '$1% complete'],
[/^(\d{2}\/\d{2}\/\d{4}) a (\d{2}\/\d{2}\/\d{4})$/, '$1 to $2'],
[/^(\d+) cargos sin foto de recibo$/, '$1 charges without a receipt photo'],
[/^(\d+) cargos$/, '$1 charges'],
[/^1 día$/, '1 day'], [/^(\d+) días$/, '$1 days'],
[/^(\d+) llevan más de 48 horas esperando firma\.$/, '$1 have waited over 48 hours for a signature.'],
[/^(\d+) pasaron las 24 horas\. El PM está esperando\.$/, '$1 are past 24 hours. The PM is waiting.'],
[/^([\d.]+) pie2$/, '$1 sq ft'], [/^([\d.]+) pie lineal$/, '$1 linear ft'], [/^([\d.]+) lote$/, '$1 lot'],
[/^([\d.]+) pieza$/, '$1 piece'], [/^([\d.]+) dia$/, '$1 day'],
[/^([\d.]+) pies²$/, '$1 sq ft'], [/^([\d.]+) pies² de espacios$/, '$1 sq ft of spaces'], [/^([\d.]+) pies lineales$/, '$1 linear ft'],
[/^1 registro sin enviar$/, '1 unsent entry'], [/^(\d+) registros sin enviar$/, '$1 unsent entries'],
[/^(\d+) KPIs? en rojo$/, '$1 KPIs in red'],
[/^(\d+) días en obra$/, '$1 days on site'],
[/^1 obra$/, '1 job'], [/^(\d+) obras$/, '$1 jobs'], [/^(\d+) obras activas$/, '$1 active jobs'],
[/^(\d+) pendientes del punch list sin cerrar$/, '$1 open punch list items'],
[/^(\d+) pendientes? fuera de los 7 días$/, '$1 past the 7 days'],
[/^(\d+) sin cerrar$/, '$1 not closed'],
[/^(\d+) h esperando$/, '$1 h waiting'], [/^([\d.]+) horas$/, '$1 hours'],
[/^(\d+) órdenes con saldo abierto$/, '$1 orders with an open balance'],
[/^Arriba de (\d+): tu punto de control PC5 no se esta haciendo$/, 'Above $1: your PC5 checkpoint is not being done'],
[/^Bloqueos abiertos fuera de SLA \((\d+) h\)$/, 'Open blockers past SLA ($1 h)'],
[/^OC en Propuesta fuera de SLA \((\d+) h\)$/, 'Change orders pending past SLA ($1 h)'],
[/^Obras sin reporte mas de (\d+) dias$/, 'Jobs without a report for over $1 days'],
[/^Cerrar ([A-Z]{2,3}-\d+)$/, 'Close $1'],
[/^Contrato (\$[\d,]+)\. Cada área con sus partidas, cantidades y unidad\.$/, 'Contract $1. Each area with its tasks, quantities and unit.'],
[/^El costo va (\d+) puntos por delante del avance$/, 'Cost is $1 points ahead of progress'],
[/^Estás financiando al cliente: (\d+) puntos de avance sin cobrar$/, "You're financing the client: $1 points of progress not collected"],
[/^Faltan (\$[\d,]+) por cobrarle al cliente$/, '$1 still to collect from the client'],
[/^Faltan (\$[\d,]+) por pagarle a subs$/, '$1 still owed to subs'],
[/^Más de (\d+) horas sin recibo es KPI rojo\.$/, 'Over $1 hours without a receipt is a red KPI.'],
[/^Ocultar los otros (\d+)$/, 'Hide the other $1'], [/^Ver los otros (\d+) indicadores$/, 'See the other $1 indicators'],
[/^Sin reporte (\d+) dias$/, 'No report for $1 days'],
[/^Si algo detiene el avance, levántalo con foto\. Compromiso de respuesta: (\d+) horas\.$/, 'If something stops the work, raise it with a photo. Answer commitment: $1 hours.'],
[/^Captúralo en el estacionamiento, no en la noche\. Límite sin autorización: (\$[\d,]+)\.$/, 'Enter it in the parking lot, not at night. Limit without approval: $1.'],
[/^Te responden los avisos en ([\d.]+) h en promedio\.$/, 'Your alerts get answered in $1 h on average.'],
[/^antes del (.+)$/, 'before $1'], [/^arranca (.+)$/, 'starts $1'], [/^arrancaba (.+)$/, 'was due $1'],
[/^autorizado (.+)$/, 'approved $1'], [/^Arrancó (.+)$/, 'Started $1'], [/^llevan ([\d.]+) h de 24$/, "it's been $1 h of 24"],
[/^contrato (\$[\d,]+)$/, 'contract $1'], [/^órdenes de cambio (\$[\d,]+)$/, 'change orders $1'], [/^costo (\$[\d,]+)$/, 'cost $1'], [/^costo real (\$[\d,]+)$/, 'actual cost $1'],
[/^cotizado (\$[\d,]+)$/, 'quoted $1'], [/^emitida (.+)$/, 'issued $1'], [/^entrega (\d.+)$/, 'delivery $1'],
[/^hace ([\d.]+) h$/, '$1 h ago'], [/^hallazgo (.+)$/, 'found $1'], [/^meta (.+)$/, 'target $1'],
[/^reporte hace (\d+) d$/, 'report $1 d ago'], [/^respondido (.+)$/, 'answered $1'],
[/^tu promedio: (\$[\d,]+)\/(.+) en 1 obra$/, function(m,a,u){ return 'your average: '+a+'/'+tr(u)+' on 1 job'; }],
[/^tu promedio: (\$[\d,]+)\/(.+) en (\d+) obras$/, function(m,a,u,n){ return 'your average: '+a+'/'+tr(u)+' on '+n+' jobs'; }],
[/^(\d+) partidas$/, '$1 tasks'], [/^(\d+) abiertos de (\d+)$/, '$1 open of $2'], [/^(\d+) puntos$/, '$1 points'],
[/^Última inspección (.+)$/, 'Last inspection $1'],
[/^Pasaron su fecha de entrega: (.+)\.$/, 'Past their delivery date: $1.'],
[/^era el (.+)$/, 'was due $1'],
[/^Foto solo en lo crítico: (\d+) puntos$/, 'Photos only where critical: $1 points'],
[/^Subiendo fotos del cierre: quedan (\d+)$/, 'Uploading close photos: $1 left'], [/^subiendo (\d+) foto\(s\)$/, 'uploading $1 photo(s)'],
[/^Foto (\d+) del cierre$/, 'Close photo $1'],
[/^Respaldo semanal activado\. Primera copia: (.+)$/, 'Weekly backup activated. First copy: $1'], [/^Copia guardada: (.+)$/, 'Copy saved: $1'],
[/^El libro tiene (\d+) problema\(s\)$/, 'The workbook has $1 problem(s)'], [/^(\d+) hojas protegidas con advertencia$/, '$1 sheets protected with a warning'],
[/^La columna (\d+) debería ser "(.+)" y dice "(.+)"(: parece que se insertó, borró o movió una columna)?\.$/, function(m,n,a,b,mv){ return 'Column '+n+' should be "'+a+'" and says "'+b+'"'+(mv?': a column seems to have been inserted, deleted or moved':'')+'.'; }],
[/^(\d+) fila\(s\) vacía\(s\) entre datos, la primera en la fila (\d+)\. Elimínalas\.$/, '$1 empty row(s) between data, the first at row $2. Delete them.'],
[/^La fila (\d+) tiene datos pero no tiene ID: el sistema no la ve\.$/, 'Row $1 has data but no ID: the system does not see it.'], [/^IDs repetidos: (.+)$/, 'Repeated IDs: $1'],
[/^(\d+) etapas presupuestadas$/, '$1 stages budgeted'],
[/^Obra (\S+) creada\. Siguiente paso: su presupuesto por etapa$/, 'Job $1 created. Next step: its budget by stage'],
[/^Falta su presupuesto por etapa: (.+)\. El PM no puede registrar su primer día hasta que lo captures\.$/, 'Missing budget by stage: $1. The PM cannot record the first day until you enter it.'],
[/^"(.*)" no es una etapa de este espacio\.$/, function(m,x){ return '"'+tr(x)+'" is not a stage of this space.'; }],
[/^Faltan: (.+)\.$/, function(m,x){ return 'Missing: '+x.split(', ').map(function(c){ var p=c.match(/^pies² de (.+)$/); if(p) return 'sq ft of '+tr(p[1]);
  var n=c.match(/^espacio (\d+)$/); return n ? 'space '+n[1] : tr(c); }).join(', ')+'.'; }],
[/^Ya hay una obra activa de (.+) en esa dirección \((\S+)\)\. ¿Crear otra de todos modos\?$/, 'There is already an active job for $1 at that address ($2). Create another one anyway?'],
[/^Cierre del (dom|lun|mar|mié|jue|vie|sáb) (\d\d\/\d\d)$/, function(m,d,f){ return 'Close for '+{dom:'Sun',lun:'Mon',mar:'Tue','mié':'Wed',jue:'Thu',vie:'Fri','sáb':'Sat'}[d]+' '+f; }],
[/^cerrado tarde · enviado el (.+)$/, 'closed late · sent on $1'],
[/^Registrado por el administrador: (.+)$/, 'Recorded by the administrator: $1'],
[/^1 dia perdido por retrabajo$/, '1 day lost to rework'], [/^(\d+) dias perdidos por retrabajo$/, '$1 days lost to rework'],
[/^te han costado (\$[\d,]+)(?:, ([\d.]+%) de lo facturado)?$/, function(m,c,p){ return 'they have cost you '+c+(p?', '+p+' of billing':''); }],
[/^Falta su presupuesto por partida: (.+)\. El PM no puede registrar su primer día hasta que lo captures\.$/, 'Missing budget by task: $1. The PM cannot record the first day until you enter it.'],
[/^Obra (\S+) creada\. Siguiente paso: su presupuesto por partida$/, 'Job $1 created. Next step: its budget by task'],
[/^Guardado, pero falta presupuesto en: (.+)\. La obra no puede arrancar todavía\.$/, function(m,x){ return 'Saved, but budget is missing for: '+x.split(', ').map(tr).join(', ')+'. The job cannot start yet.'; }],
[/^la obra ya puede arrancar$/, 'the job can start now'],
[/^Sin datos todavia\. (.+)$/, function(m,x){ return 'No data yet. '+tr(x); }],
[/^(.+) quedaría en dos obras \((.+)\) el (.+)$/, function(m,s,o,d){ return s+' would be on two jobs ('+o.replace(' y ',' and ')+') on '+d; }],
[/^Falta confirmación escrita: (.+) en (\S+), llega el (.+)$/, 'Written confirmation missing: $1 on $2, arriving $3'],
[/^Va a entregar el (.+): (\d+) días hábiles después de lo comprometido$/, 'Will deliver on $1: $2 business days after the commitment'],
[/^Cumplimiento del plan la semana pasada: (\d+%) \((\d+) de (\d+)\)$/, 'Plan completion last week: $1 ($2 of $3)'],
[/^Entrega prevista:? (.+)$/, 'Expected delivery $1'], [/^el plan decía (.+)$/, 'the plan said $1'],
[/^Propuesta según la plantilla: (\d+) días hábiles\.$/, 'Proposed from the template: $1 business days.'],
[/^Más corta que lo que da la plantilla: (\d+) días hábiles, entrega el (.+)\.$/, 'Shorter than the template: $1 business days, delivery on $2.'],
[/^\+(\d+) espera$/, '+$1 wait'], [/^real ([\d.]+)$/, 'actual $1'],
[/^Duraciones sugeridas: (\d+) partidas$/, 'Suggested durations: $1 tasks'],
[/^Llega: (.+)$/, 'Arriving: $1'],
[/^(dom|lun|mar|mié|jue|vie|sáb) (\d\d\/\d\d)$/, function(m,d,f){ return {dom:'Sun',lun:'Mon',mar:'Tue','mié':'Wed',jue:'Thu',vie:'Fri','sáb':'Sat'}[d]+' '+f; }],
[/^(.+) cobra por dia: se registra como dia completo o medio dia\.$/, '$1 is paid by the day: record a full day or a half day.'],
[/^(.+) ya tiene (un dia completo|medio dia) registrado el (\S+?)(?: en (.+))?\. Un trabajador por dia no puede pasar de un dia sumando todas las obras\.$/,
  function(m,n,c,f,o){ return n+' already has '+(c==='medio dia'?'a half day':'a full day')+' recorded on '+f+(o?' on '+o:'')+'. A daily-rate worker cannot exceed one day across all jobs.'; }],
[/^(.+) ya tiene ([\d.]+) h registradas el (\S+?)(?: en (.+))?; con estas serian ([\d.]+) h\. El maximo es 16 al dia\.$/,
  function(m,n,y,f,o,t){ return n+' already has '+y+' h recorded on '+f+(o?' on '+o:'')+'; with these it would be '+t+' h. The maximum is 16 a day.'; }],
[/^Atrasada (\d+) días hábiles: la entrega era el (.+)$/, '$1 business days late: delivery was due $2'],
[/^Detrás del plan: debería ir en (\d+%), va en (\d+%)$/, 'Behind plan: should be at $1, is at $2'],
[/^Atrasada 1 dia$/, '1 day late'], [/^Atrasada (\d+) dias$/, '$1 days late'],
[/^Sin trabajo: ([^.]+)(?:\. (.+))?$/, function(m,x,n){ return 'No work: '+tr(x)+(n?'. '+n:''); }],
[/^Este cargo supera el limite de (\$[\d,]+)\. Ya le aparece al administrador para revisarlo\.$/, 'This charge is over the $1 limit. The administrator will see it to review.'],
[/^¿Por qué se quita "(.+)" de esta obra\? \(queda registrado\)$/, function(m,p){ return 'Why is "'+tr(p)+'" being removed from this job? (it is logged)'; }],
[/^Nombre de la partida nueva para (.+) \(solo esta obra\):$/, function(m,a){ return 'Name of the new task for '+tr(a)+' (this job only):'; }],
[/^(\d+) falta\(s\) registrada\(s\)$/, '$1 no-show(s) recorded'],
[/^La obra va en (\d+%): (\d+) partida\(s\) sin terminar\. ¿Cerrar de todos modos\?$/, 'The job is at $1: $2 task(s) not finished. Close anyway?'],
[/^(\d+) partida\(s\) sin terminar: (.+?)(…)?\. Termínalas, o quítalas si no se hicieron en esta obra\.$/, function(m,n,l,mas){
  return n+' task(s) not finished: '+l.split(', ').map(function(x){ return x.split(' · ').map(tr).join(' · '); }).join(', ')+(mas||'')+'. Finish them, or remove them if they were not done on this job.'; }],
[/^Esa partida no esta en (.+)\.$/, function(m,a){ return 'That task is not in '+tr(a)+'.'; }],
[/^Esa partida ya esta en (.+)\.$/, function(m,a){ return 'That task is already in '+tr(a)+'.'; }],
[/^Esa orden ya esta (\S+)\.$/, function(m,x){ return 'That order is already '+tr(x.charAt(0).toUpperCase()+x.slice(1)).toLowerCase()+'.'; }],

[/^\+?(\d+) no aplican?$/, function(m,n){ return (m.charAt(0)==='+'?'+':'')+n+' N/A'; }],
[/^No aplican?: (.+)$/, 'N/A: $1'],
[/^(\d+) punto\(s\) sin cumplir\. Se registra como defecto y le llega al administrador\. ¿Guardar así\?$/, '$1 item(s) not passing. They will be logged as defects and sent to the administrator. Save anyway?'],
[/^Marcaste (\d+) preguntas como No aplica y solo revisaste (\d+)\. El administrador lo va a ver\. ¿Seguro que no aplican\?$/, 'You marked $1 questions as N/A and only checked $2. The administrator will see this. Are you sure they don\'t apply?'],
[/^Este cargo supera tu limite sin autorizacion \((\$[\d,]+)\)\. Avisale al administrador\.$/, 'This charge is over your limit without approval ($1). Let the administrator know.'], [/^(\d+) inspecciones$/, '$1 inspections'],
[/^✓ Prueba de inundación: ([\d.]+) h sin fugas$/, '✓ Flood test: $1 h with no leaks'],
[/^Prueba de inundación: ([\d.]+) h sin fugas$/, 'Flood test: $1 h with no leaks'],
[/^Prueba de inundación en curso$/, 'Flood test running'],
[/^Incluye la prueba de inundación de 24 horas$/, 'Includes the 24-hour flood test'],
[/^La última prueba de inundación marcó fuga$/, 'The last flood test found a leak'],
[/^Falló: (.+)$/, 'Failed: $1'], [/^PM (.+)$/, 'PM $1'], [/^Sub: (.+)$/, 'Sub: $1'], [/^No se guardó: (.+)$/, 'Not saved: $1'],
[/^Qué se revisa \((\d+)\)$/, "What's checked ($1)"],
[/^Ver las (\d+) respuestas$/, 'See all $1 answers'],
[/^(\d+) (?:foto es|fotos son) de otro día \((.+)\)\. Revisa que sean de hoy\.$/, function(m,n,f){ return n+(n==='1'?' photo is':' photos are')+' from another day ('+f+'). Make sure they are from today.'; }],
[/^(\d+) (?:foto es|fotos son) de otro día \((.+)\)\. El cierre es de hoy\. ¿Enviar de todos modos\?$/, function(m,n,f){ return n+(n==='1'?' photo is':' photos are')+' from another day ('+f+'). The close is for today. Send anyway?'; }],
[/^(\d+) (?:foto es|fotos son) de otro día \((.+)\)\. Una inspección tiene que mostrar el estado de hoy\. ¿Guardar de todos modos\?$/, function(m,n,f){ return n+(n==='1'?' photo is':' photos are')+' from another day ('+f+'). An inspection has to show today\'s condition. Save anyway?'; }],
[/^1 foto lista$/, '1 photo ready'], [/^(\d+) fotos listas$/, '$1 photos ready'], [/^Preparando (\d+)…$/, 'Preparing $1…'],
[/^Enviando (\d+) fotos…$/, 'Sending $1 photos…'],
[/^Máximo (\d+) fotos por cierre\. Se quedaron las primeras (\d+)\.$/, 'Up to $1 photos per close. The first $2 were kept.'],
[/^Cierre de día del (.+)$/, 'Daily close of $1'], [/^Gasto (\$[\d,.]+)$/, 'Expense $1'],
[/^(\d+) registros anulados$/, '$1 entries voided'], [/^([\d.]+) h de cuadrilla$/, '$1 crew hours'],
[/^obra ([\d.]+) pies²$/, 'job $1 sq ft'], [/^([\d.]+) h sin fugas$/, '$1 h with no leaks'], [/^Prueba cerrada$/, 'Test closed'],
[/^Registrada con (\d+) defecto\(s\)$/, 'Recorded with $1 defect(s)'], [/^(\d+) campo\(s\) corregido\(s\)$/, '$1 field(s) fixed'],
[/^Respondido en ([\d.]+) h$/, 'Answered in $1 h'],
[/^OC (\S+) emitida con ([\d.]+%) de margen$/, 'CO $1 issued with $2 margin'],
[/^Orden (\S+) emitida$/, 'Order $1 issued'], [/^Registrado (\S+)$/, 'Recorded $1'],
[/^Obra (\S+) creada con (\d+) espacio\(s\) \+ Generales$/, 'Job $1 created with $2 space(s) + General conditions'],
[/^saldo (\$[\d,.]+)$/, 'balance $1'], [/^margen ([\d.]+%)$/, 'margin $1'], [/^garantía vence (.+)$/, 'warranty expires $1'],
[/^Tipo creado con (\d+) partidas$/, 'Type created with $1 tasks'], [/^(\d+) partidas presupuestadas$/, '$1 tasks budgeted'],
[/^(.+) reactivado$/, '$1 reactivated'], [/^(.+) dado de baja$/, '$1 deactivated'],
[/^Guardado\. Ojo: (.+)$/, function(m,x){ return 'Saved. Heads up: '+x.split('; ').map(tr).join('; '); }],
[/^su seguro vencio el (.+)$/, 'their insurance expired on $1'], [/^su licencia vencio el (.+)$/, 'their license expired on $1'],
[/^(.+) requiere licencia estatal en Texas y no tiene una registrada$/, function(m,o){ return tr(o)+' requires a Texas state license and none is on file'; }],
[/^Puntos de control sin aprobar: (.+)$/, function(m,x){ return 'Checkpoints not approved: '+x.split(', ').map(function(s){ var i=s.lastIndexOf(' '); return tr(s.slice(0,i))+s.slice(i); }).join(', '); }],
[/^No hay prueba de inundacion documentada en (.+)$/, function(m,a){ return 'No flood test documented for '+tr(a); }],
[/^La orden (\S+) no es de esta obra\.$/, 'Order $1 is not from this job.'],
[/^No se encontro (\S+) en (\S+)\.?$/, '$1 not found in $2.'], [/^No se encontro (\S+)\.$/, '$1 not found.'],
[/^No se encontro el gasto (\S+)$/, 'Expense $1 not found'], [/^No se encontro la orden (\S+)$/, 'Order $1 not found'],
[/^Ese registro tiene mas de (\d+) horas\. Pidele al administrador que lo corrija\.$/, 'That record is over $1 hours old. Ask the administrator to fix it.'],
[/^Ese registro tiene mas de (\d+) horas\. Pidele al administrador que lo anule\.$/, 'That record is over $1 hours old. Ask the administrator to void it.'],
[/^Antes de cerrar "(.+)" de (.+) hay que aprobar la inspeccion (.+)\. Hazla desde Obra > Calidad y luego cierra el dia, o registra el dia sin marcarla como terminada\.$/,
  function(m,p,a,h){ return 'Before closing "'+tr(p)+'" in '+tr(a)+', inspection '+tr(h)+' must be approved. Do it from Job > Quality and then close the day, or log the day without marking it done.'; }],
[/^La impermeabilizacion no se aprueba sin la prueba de inundacion terminada y sin fugas\. Inicia la prueba desde la pantalla de calidad\.$/, "Waterproofing can't be approved without a completed flood test with no leaks. Start the test from the quality screen."],
[/^Llevan ([\d.]+) horas\. La prueba es de 24\. Cerrarla antes no prueba nada; dejala correr y vuelve\.$/, "It's been $1 hours. The test is 24. Closing it early proves nothing; let it run and come back."],
[/^Este cargo supera el limite de (\$[\d,]+)\. Avisale al administrador\.$/, 'This charge is over the $1 limit. Let the administrator know.'],
[/^Usuario o PIN incorrectos\. Te queda 1 intento\.$/, 'Wrong username or PIN. 1 attempt left.'],
[/^Usuario o PIN incorrectos\. Te quedan (\d+) intentos\.$/, 'Wrong username or PIN. $1 attempts left.'],
[/^Esta OC sale con ([\d.]+)% de margen, abajo de tu minimo de (\d+)%\. Precio sugerido: (\$[\d,]+)\. Quieres emitirla de todos modos\?$/, 'This CO comes out at $1% margin, below your minimum of $2%. Suggested price: $3. Issue it anyway?'],
[/^Este sub todavia no confirma por escrito la orden (\S+)\. Un anticipo antes de la confirmacion es dinero sin compromiso\. Pagar de todos modos\?$/, "This sub hasn't confirmed order $1 in writing yet. An advance before confirmation is money without commitment. Pay anyway?"],
[/^El PM todavia no aprueba el trabajo de la orden (\S+)\. La regla es que el sub cobra contra trabajo aprobado\. Pagar de todos modos\?$/, "The PM hasn't approved the work on order $1 yet. The rule is subs get paid against approved work. Pay anyway?"],
[/^Sobre (.+?): (.+)\. Pagarle asi te deja expuesto\. Continuar\?$/, function(m,s,x){ return 'About '+s+': '+x.split('; ').map(tr).join('; ')+'. Paying them like this leaves you exposed. Continue?'; }],
[/^Con este pago llevarias (\$[\d,]+) contra una orden de (\$[\d,]+)\. Si es trabajo extra, va en una orden de cambio, no aqui\. Continuar\?$/, "With this payment you'd be at $1 against a $2 order. If it's extra work, it goes on a change order, not here. Continue?"],
[/^Ya existe un subcontratista con ese nombre \((\S+)\)\. Editalo en vez de darlo de alta dos veces, o su historial se parte en dos\.$/, 'A subcontractor with that name already exists ($1). Edit it instead of adding it twice, or their history splits in two.'],
[/^Esa partida ya existe en (.+)\.$/, function(m,t){ return 'That task already exists in '+tr(t)+'.'; }],
[/^Esa partida ya tiene avance o mano de obra registrada\. Renombrala en vez de borrarla, para no romper el historico de costos\.$/, 'That task already has progress or labor recorded. Rename it instead of deleting it, so the cost history stays intact.'],
[/^Ya existe un tipo de obra llamado (.+)\.$/, 'A job type called $1 already exists.'],
[/^Hay (\d+) pendiente\(s\) de dinero en esta obra\. Si la cierras así, ese dinero queda sin cobrar\. ¿Cerrar de todos modos\?$/, "There are $1 money item(s) pending on this job. If you close it like this, that money stays uncollected. Close anyway?"],
[/^¿Dar de baja a (.+?)\? Se conserva su historial y deja de aparecer al emitir órdenes nuevas\.(?: Tiene (\d+) orden\(es\) abierta\(s\): esas siguen vigentes\.)?$/, function(m,s,n){ return 'Deactivate '+s+'? Their history is kept and they stop showing up for new orders.'+(n?' They have '+n+' open order(s): those remain active.':''); }],
[/^¿Borrar "(.+)" del catálogo de (.+)\?$/, function(m,p,t){ return 'Delete "'+tr(p)+'" from the '+tr(t)+' catalog?'; }],
[/^Cerrar (\S+)$/, 'Close $1'],
[/^(.+) \+ (.+)$/, function(m,a,b){ var x=tr(a), y=tr(b); return (x!==a && y!==b) ? x+' + '+y : m; }],
[/^al día hace ([\d]+) s$/, 'up to date $1 s ago'], [/^al día hace ([\d]+) min$/, 'up to date $1 min ago'], [/^al día ahora$/, 'up to date now'],
[/^sesión expirada, recarga la página$/, 'session expired, reload the page'],
[/^(\d+) espacios?$/, '$1 space(s)'],
[/^Tu sesión expiró\. Entra de nuevo para enviar (\d+) registros? pendientes?\.$/, function(m,n){ return 'Your session expired. Sign in again to send '+n+' pending entr'+(n==='1'?'y.':'ies.'); }],
"""

# --- los nombres con acentos y ñ se traducen igual que su versión anterior sin acentos (ver acentos.py);
#     las versiones viejas se quedan, para que los libros anteriores se sigan traduciendo
import os as _o, sys as _s
_s.path.insert(0, _o.path.dirname(_o.path.abspath(__file__)))
from acentos import corregir as _corregir
for _k in list(EN):
    _n = _corregir(_k)
    if _n != _k and _n not in EN:
        EN[_n] = EN[_k]
